Suppression listes numéros lors de l'édition
BaseAdresseNationale/mes-adresses pull request #417
Opened 2021-09-28 16:02 UTC by Maxine-Le-Pennec

Liste des numéros et barre de recherche masquées lors de l'édition ou création d'un numéro.

<img width="501" alt="Capture d’écran 2021-09-28 à 17 58 31" src="https://user-images.githubusercontent.com/66621960/135123576-048c7e4b-a57f-4aa9-92f0-f34e3a1cbd31.png">
<img width="500" alt="Capture d’écran 2021-09-28 à 17 58 44" src="https://user-images.githubusercontent.com/66621960/135123590-e6e1b4ab-c028-43f7-b044-d24c157904fc.png">

2021-09-29 07:03 UTC, GllmR reviewed
Il serait intéressant d'en profiter pour masquer le composant `<GroupedActions />`pour éviter d'avoir les boutons affichés en cas d'édition d'un numéro.

![image](https://user-images.githubusercontent.com/56537238/135219231-29a2b4d8-27ae-40c0-a004-1481dd29035b.png)

2021-09-29 09:08 UTC, GllmR commented on pages/bal/voie.js
> +            !isEditing && (
Cette condition n’est pas nécessaire

2021-09-30 09:23 UTC, tmerlier commented
En passant par la création d'adresse de la carte, la liste des numéros disparait car le mode édition est activé. La liste des numéros ne devrait pas être cacher si l'édition ne concerne pas la voie.

Une autre solution serait de migrer le formulaire de création d’adresse dans le menu latéral, mais c'est une modification majeure et ne peut pas être traitée sur cette PR pour le moment.

![Capture d’écran 2021-09-30 à 11 19 29](https://user-images.githubusercontent.com/7040549/135425143-25fc157b-65c7-47b1-8772-0dd9d37419dd.png)

2021-09-30 09:33 UTC, tmerlier requested changes
La quasi totalité du rendu de la page dépend de `isEditing` désormais. Il serait bien plus simple de simplement afficher le formulaire si `isEditing === true` et sinon afficher la liste des numéros de la voie.

Mieux encore serait de vérifier si `editingId` correspond à un `id` des numéros de la voie afin d'afficher le formulaire ou alors d'afficher la liste des numéros en bloquant l'édition. Cela permettrait de ne pas affiche un menu vierge si le formulaire de création d'adresse est ouvert.

2021-09-30 09:33 UTC, tmerlier commented on pages/bal/voie.js
> +                disabled={isAdding || isEditing}
Si ce bouton n'est plus affiché si `isEditing === true` alors cette condition est obsolète.

2021-09-30 09:33 UTC, tmerlier commented on pages/bal/voie.js
> +      {isGroupedActionsShown && numeros && !isEditing && (
`isEditing` pour être ajouté au calcule de `isGroupedActionsShown`.

2021-10-04 15:09 UTC, GllmR commented
Lorsque le composant `AdresseEditor` est ouvert, le composant `groupedAction` est encore affiché.

2021-10-04 15:37 UTC, Maxine-Le-Pennec reviewed
Lorsque l'on créer un numéro depuis la carte, les actions d'édition à gauche sont bien disable.
![Capture d’écran 2021-10-04 à 17 33 59](https://user-images.githubusercontent.com/66621960/135880461-99d07284-1f22-4f0c-87f3-bfa3ea1165a1.png)


Par contre, si on ne ferme pas le menu de création d'adresse depuis la carte, que l'on clique sur le nom de la commune dans le fil d'Arianne, puis que l'on reclique sur un nom de voie, la création d'adresse est toujours possible sous la carte et l'édition est de nouveau possible dans le menu de gauche

![Capture d’écran 2021-10-04 à 17 31 12](https://user-images.githubusercontent.com/66621960/135880324-4820af59-df25-4dbd-a2fe-7d2f2ce8673d.png)

2021-10-04 17:08 UTC, tmerlier commented
Ce bug est aussi en prod actuellement, il concerne plus le formulaire de création d'adresse que la page voie en elle même. J'ai créé une issue #429

2021-10-05 08:15 UTC, GllmR approved these changes

2021-10-05 09:53 UTC, tmerlier approved these changes

2021-10-05 09:56 UTC, merged