Vsagniez/fondcarte
BaseAdresseNationale/mes-adresses pull request #463
Opened 2021-12-01 14:02 UTC by vinsag

Utilisation des fonds de cartes vecteur tuilés IGN. Suppression du style toponyme pour les valeurs suivantes : routier_borne, routier_numeor_lin et routier_donyme_lin

2021-12-01 14:31 UTC, tmerlier requested changes
Il reste plusieurs petits détails pour valider l'intégration du plan:
- [x] Les routes ne doivent pas disparaitre lorsqu'on approche du zoom 18
- [x] Le plan cadastrale ne doit pas s'afficher au zoom 19
- [ ] Retirer les toponymes restant
- [x] Ajouter les attributions

2021-12-01 14:31 UTC, tmerlier commented on components/map/styles/vector.json
> +		},
```suggestion
  "plan_ign": {
   "type": "vector",
   "tiles": [
    "https://wxs.ign.fr/choisirgeoportail/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf"
   ],
   "scheme": "xyz"
  },
```

2021-12-01 14:33 UTC, tmerlier commented
Le fichier `vector.json` souffre de quelques soucis d'indentation également.

2021-12-01 15:29 UTC, vinsag commented
@tmerlier :
Pour le commentaire "Les routes ne doivent pas disparaitre lorsqu'on approche du zoom 18".
Nous ne pouvons pas changer ce parametrage qui est sur toutes les cartes.
Je vais modifier les autres

2021-12-01 15:47 UTC, tmerlier commented
> @tmerlier :
> Pour le commentaire "Les routes ne doivent pas disparaitre lorsqu'on approche du zoom 18".
> Nous ne pouvons pas changer ce parametrage qui est sur toutes les cartes.
> Je vais modifier les autres

Tout peut être adapté depuis le fichier `vector.json` grâce aux styles de chaque layer. Ici ce sont les layers `Routier …` sur lesquels il faut intervenir. Passer le `maxzoom` de `18` à `20` permettra de les rendre visible pour commencer. Une fois visible on pourra certainement ajuster plus finement le reste.

2021-12-02 16:13 UTC, vinsag commented
@tmerlier : Les 4 points ont été résolus. A voir s'il faut encore modifier des zooms, j'ai pu en oublier.
Il reste un problème : l'affichage du cadastre se fait bien au niveau du plan mais le cadastre ne s'affiche pas sur l'ortho à cause d'un conflit sur le fichier components/map/layers/cadastre.js pour le text-font

2021-12-02 17:13 UTC, tmerlier commented
Les routes et leurs contours disparaissent toujours comme on peut le voir sur cette capture :
https://user-images.githubusercontent.com/7040549/144469082-3d7d7633-703f-44db-adc9-2b4e58274662.mov

Il faut certainement intervenir sur la propriété `visibility` de ces layers.

-----
Pour ce qui est des toponymes, on peut voir que certains d'entre eux sont toujours visible. C'est justement ceux-là qui peuvent nous poser problème pour l'adressage.

![Capture d’écran 2021-12-02 à 17 56 24](https://user-images.githubusercontent.com/7040549/144468837-9a18e3d0-1ad2-49c0-8a06-86ea90b457d7.png)

-----

Et enfin pour ce qui est du cadastre, il semblerait simplement que la font `Source Sans Pro Regular` ne soit pas fourni par le fond orthophoto. Je vois deux solutions:
- Trouver une font partagé à la fois par le fond vector et orthopho
- Supprimer la propriété `text-font` du `layout` afin d'utiliser automatique la font par défaut

2021-12-08 15:17 UTC, vinsag commented
Bonjour, j'ai passé les différentes couches du plan vecteur tuilé au niveau de zoom 21 et j'ai mis en invisible les couches cadastre en invisible pour le plan vecteur tuilé.

2021-12-17 15:08 UTC, vinsag commented
Bonjour,
Je viens de passer une nouvelle version avec les modifications suivantes:
- Le cadastre s'affiche maintenant sur orthophoto et plan ign.
- Modification des couleurs de certains axes qui disparait avec la couleur blanche sous fond blanc à partir d'un certain zoom.
- Suppression de certains toponymes : dans le code toponyme_localite_ponc

2021-12-17 16:07 UTC, tmerlier commented
Nous sommes ok pour l'affichage des routes et la gestion de la polices dans deux fonds de carte ✅

Je viens de jeter un oeil aux toponymes à ne pas afficher et il semblerait que ce soit tous les layers commençant par `toponyme localite ...`. On peut d'ailleurs les retirer complètement du style plutôt que de passer `visibility: none`.

2022-01-14 09:25 UTC, tmerlier requested changes
Attention, mise à part le changement de font, le fichier `vector.json` ne devrait montrer aucune autre modification.

2022-01-14 09:25 UTC, tmerlier commented on components/map/map.js
> +    case 'planIGN':
```suggestion
    case 'plan-ign':
```

2022-01-14 09:25 UTC, tmerlier commented on components/map/style-selector.js
> +  {label: 'Plan IGN(Version Bêta)', value: 'planIGN'},
```suggestion
  {label: 'Plan IGN(Version Bêta)', value: 'plan-ign'},
```

2022-01-14 09:25 UTC, tmerlier commented on components/map/styles/ortho.json
> +	"sprite": "https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/sprite/PlanIgn",
Qu'est-ce que permet l'ajout de ce sprite ?

2022-01-14 09:48 UTC, vinsag commented on components/map/styles/ortho.json
> +	"sprite": "https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/sprite/PlanIgn",
La ligne sprite peut être supprimée, elle ne sert pas effectivement

2022-01-17 12:38 UTC, jdesboeufs approved these changes

2022-01-17 12:39 UTC, merged