Refonte du chargement des pages et des contextes
BaseAdresseNationale/mes-adresses pull request #477
Opened 2022-01-14 16:02 UTC by tmerlier

# ⚠️ Attention cette PR est basée sur la branche [Intégration de l'API de dépôt #471](https://github.com/BaseAdresseNationale/mes-adresses/pull/471) qui n'est pas encore mergée

-------

## Description
L'outils comportement de nombreux contextes de données et de lourds composants qui ne sont nécessaires que pour l'outil d'édition. Hors ceux-ci sont actuellement chargés même en dehors de l'outils d'édition.

Cette agencement pose deux problèmes importants : 
- Un problème de performances, car leur chargement relativement important affecte inutilement les autres pages
- De conditions, car en étant présent sans pouvoir recevoir les données nécessaires à leur bon fonctionnement il est nécessaire de vérifier la présence de chaque variable afin d'assurer un comportement viable.

De plus, l'arrivé de l'API de dépôt et la migration des bases locales a mit un terme définitif au BAL multi-communale. Cette PR supprime donc la page `/bal`, retire les messages d'avertissement liés à ces BAL et met à jour la documentation.

## Résumé
- Suppression du système de layout `fullscreen/sidebar` désormais devenu optionnel. Le layout `sidebar` n'étant utilisé que pour l'outil décision, celui-ci utilise le layout directement.
- Un nouveau composant/layout `<Editor />`  qui s'occupe d'embarquer tout ce qui est nécessaire à l'outil d'édition (les contextes, composants du menu latéral ainsi que la carte)
- Les variables comme `baseLocale` et `commune` ne peuvent plus être optionnelles et leur gestion à travers l'application a été simplifiée.
- Désormais seul le contexte `BalDataContext` manipule et fourni les variables `baseLocale`, `commune`, `voie` et `toponyme`. Si celle-ci sont modifier alors l'intégralité de l'application est mis à jour automatiquement.
- Suppression du support des BAL multi-communale

----

## To do
Afin de ne plus considérer cette PR comme un brouillon, il est nécessaire de : 

- [ ] Merger Intégration de l'API de dépôt côté front #471
- [ ] Merger Intégration de l'API de dépôt côté back [#303](https://github.com/BaseAdresseNationale/api-bal/pull/303)
- [ ] S'assurer qu'il n'existe plus de BAL multi-communale

2022-02-17 11:42 UTC, cedric-famibelle-pronzola requested changes
Il y a un double `header` sur la page erreur 404

![error-page](https://user-images.githubusercontent.com/45098730/154473769-964d63ef-9a10-4810-bf8b-431980412e8b.png)

la page `/all` est inaccessible 

![all-page](https://user-images.githubusercontent.com/45098730/154473943-3c4220b4-d5bd-41b3-a3d2-d167798003b0.png)

2022-02-22 13:35 UTC, tmerlier commented
Je ne rencontre aucun problème sur la page `/all`. @cedric-famibelle-pronzola est-ce que tu peux me confirmer que tout est à jour de ton côté stp ?

2022-03-18 15:10 UTC, GllmR approved these changes

2022-03-21 13:06 UTC, cedric-famibelle-pronzola requested changes
- La création de BAL de démo est KO.
- Lors de la certification en masse en passant par les paramètres, il y a une erreur
![pr-context](https://user-images.githubusercontent.com/45098730/159266923-eb59ad86-0dfe-4742-a0bb-4cdf6fe5626b.png)

2022-03-21 18:14 UTC, cedric-famibelle-pronzola approved these changes

2022-03-22 08:52 UTC, Maxine-Le-Pennec approved these changes

2022-03-25 07:21 UTC, merged