Permet d'enlever une base adresse locale de la liste sans la supprimer
BaseAdresseNationale/mes-adresses pull request #488
Opened 2022-02-11 08:05 UTC by cedric-famibelle-pronzola

resolves #487 

- Ajout du localstorage `hidden-bal` dans le context
- Ajout d'un bouton permettant de "cacher" la base adresse locale
- Ajout d'une alerte permettant de restaurer les bases adresses locales cachées

Capture vidéo :

https://user-images.githubusercontent.com/45098730/153556379-d15f4993-8117-4c32-992a-627e7b1aefc6.mp4

2022-02-15 09:25 UTC, tmerlier requested changes

2022-02-15 09:25 UTC, tmerlier commented on components/hidden-bal.js
> +            Pour l{hiddenBalList.length > 1 ? 'es ' : '’'}afficher
Calculer à l'avancer s'il y a plusieurs BAL permettrait de faciliter la lecture du code et éviter les répétitions.

`const isPlural = hiddenBalList.length > 1`

```suggestion
            Il y a {hiddenBalList.length} base{isPlural ? 's' : ''} adresse{isPlural ? 's' : ''} locale{isPlural ? 's' : ''} non listée{isPlural ? 's' : ''}.
            Pour l{isPlural ? 'es ' : '’'}afficher
```

2022-02-15 09:25 UTC, tmerlier commented on components/hidden-bal.js
> +          <Button appearance='primary' marginLeft='1em' onClick={() => showAllBal()}>Cliquez ici</Button>
```suggestion
          <Button appearance='primary' marginLeft='1em' onClick={showAllBal}>Cliquez ici</Button>
```

2022-02-15 09:25 UTC, tmerlier commented on components/hidden-bal.js
> +  }
Inutile de créer une state et de s'embêter à la synchroniser avec `hiddenBal`. Autant utiliser directement `hiddenBal`.

2022-02-15 13:51 UTC, tmerlier commented
Je suis un peu embêtant concernant l'UI, l'emplacement du bouton pour cacher une BAL de la liste me parait étrange.
Concernant l'UX, je trouve le warning peu trop voyant (presque alarmant). De plus, ré-afficher toutes les BAL sans pouvoir faire le tri me semble handicapant. 

Je crains également que des utilisateurs perdent leur BAL en les cachants.

Je propose de modifier un peu l'UI et de cacher les BAL dans une liste secondaire qui pourrait se plier/déplier (pliée par défaut) et où chaque BAL pourrait être ré-afficher une à une.
En revanche, je sèche pour l'emplacement de bouton permettant de cacher… Peut-être à côté de la suppression (?) mais cela ne me semble pas idéal non plus.

2022-02-15 19:42 UTC, jdesboeufs commented
Il faut permettre à l'utilisateur de vraiment détacher la BAL.
Les chefs de file accompagnent et en ont des dizaines. Pareil pour les prestataires. À un moment ils passent la main.

2022-02-16 07:22 UTC, cedric-famibelle-pronzola commented
@jdesboeufs "Détacher" c'est à dire ?
@tmerlier pour lister les bal cachées on peut utiliser un `dialog` comme dans la capture ?
Concernant le warning, est-ce que l'alerte est appropriée même en bleu ?

https://user-images.githubusercontent.com/45098730/154215368-bb968be4-48dc-4b6f-b05b-e5d1a82bdac8.mp4

2022-02-16 10:18 UTC, tmerlier commented
Voici ce que je propose:
https://user-images.githubusercontent.com/7040549/154244193-65beb026-70f5-489c-bfb7-6b23a5e633cd.mov

2022-02-21 16:17 UTC, tmerlier approved these changes

2022-02-22 15:44 UTC, GllmR approved these changes

2022-03-01 14:24 UTC, Maxine-Le-Pennec commented
> resolves #487
> 
> * Ajout du localstorage `hidden-bal` dans le context
> * Ajout d'un bouton permettant de "cacher" la base adresse locale
> * Ajout d'une alerte permettant de restaurer les bases adresses locales cachées
> 
> Capture vidéo :
> 
>  bal-hide-2022-02-11_12.01.56.mp4

Tout fonctionne de mon côté sans perte au niveau du localStorage.
J'ai juste deux réflexions en terme d'UI/UX :

- Je trouve que le bouton `Afficher vos Bases Adresses Locales masquées` n'est pas assez visible.
- Est ce que ça ne serait pas pertinent (si possible) de pouvoir supprimer la BAL lorsqu'elle est dans la liste des bal masquées ?
- Peut être pouvoir sélectionner plusieurs bal à afficher/masquer

2022-03-02 15:07 UTC, tmerlier commented
> 

Cette fonctionnalité est spécifique aux utilisateurs chefs de files (expert) et est donc volontairement limitée. Ça présence ne doit pas perturber la navigation des utilisateurs plus amateur, c'est pourquoi le message est peut visible et que cette fonctionnalité n'a pas de sélection multiple.

2022-03-04 08:20 UTC, merged