Remplacer les boutons avec une action de redirection par de vrais liens #491
BaseAdresseNationale/mes-adresses pull request #493
Opened 2022-02-18 09:27 UTC by vinsag

Remplacement des <Button onClick par <Button is='a'

2022-02-22 09:50 UTC, tmerlier commented
Il manque plusieurs liens qui n'ont pas étaient modifiés :
- [ ] components/user-bases-locales.js ligne 64
- [ ] layouts/dashboard.js ligne 35
- [ ] pages/all.js ligne 21
- [ ] pages/index.js ligne 24
- [ ] pages/new.js ligne 9

2022-02-22 09:56 UTC, tmerlier commented
Je me rend compte que le comportement n'est pas le bon. En effet, cliquer sur les "nouveaux" liens provoque un rechargement complet de la page. Cela est dû au fait que nous ne bénéficions plus du `prefetch` de Nextjs (avant possible grâce à next/router).

Mais il est tout de même possible d'en bénéficier en utilisant [`next/link`](https://nextjs.org/docs/api-reference/next/link).
Exemple:
```
<Link href='/' passHref>
  <Button is='a'>
    Cliquez ici
  </Button>
</Link>
```

2022-02-22 09:57 UTC, tmerlier requested changes
Il manque plusieurs liens qui n'ont pas étaient modifiés :
- [X ] components/user-bases-locales.js ligne 64
- [ ] layouts/dashboard.js ligne 35
- [ ] pages/all.js ligne 21
- [ X] pages/index.js ligne 24
- [ ] pages/new.js ligne 9

J'ai ajouté les pages:
pages/_error.js
pages/404.js

2022-02-23 09:54 UTC, vinsag commented
1)Je ne vois pas comment corriger le fichier pages/all.js :+1: 
 const onCreate = useCallback(() => {
    Router.push('/new')
  }, [])
dois je faire : 
 <Link href='/new' passHref>
          <Button is='a'>
          </Button>
        </Link>

2) dans le fichier pages/_error.js : L'appel de next/link ne marche pas, je ne comprends pas trop

3) Je ne trouve pas le fichier pages/new.js ligne 9

2022-02-23 13:36 UTC, vinsag commented
> > 1)Je ne vois pas comment corriger le fichier pages/all.js +1 const onCreate = useCallback(() => { Router.push('/new') }, []) dois je faire :
> > 
> > 2. dans le fichier pages/_error.js : L'appel de next/link ne marche pas, je ne comprends pas trop
> > 3. Je ne trouve pas le fichier pages/new.js ligne 9
> 
>     1. Il faut se débarrasser de la fonction et la remplacer par le lien, de la même façon que pour les autres.
> 
>     2. Il n'y a pas de raison. Si tu es sûr que ton import est bien fait alors je veux bien un peu plus de détails pour t'aider.
> 
>     3. Pardon, c'est une erreur de ma part, mais je ne sais plus à qu'elle oubli je faisais référence…



> > 1)Je ne vois pas comment corriger le fichier pages/all.js +1 const onCreate = useCallback(() => { Router.push('/new') }, []) dois je faire :
> > 
> > 2. dans le fichier pages/_error.js : L'appel de next/link ne marche pas, je ne comprends pas trop
> > 3. Je ne trouve pas le fichier pages/new.js ligne 9
> 
>     1. Il faut se débarrasser de la fonction et la remplacer par le lien, de la même façon que pour les autres.
> 
>     2. Il n'y a pas de raison. Si tu es sûr que ton import est bien fait alors je veux bien un peu plus de détails pour t'aider.
> 
>     3. Pardon, c'est une erreur de ma part, mais je ne sais plus à qu'elle oubli je faisais référence…

Il me reste à modifier le point 1

2022-02-28 14:18 UTC, tmerlier approved these changes

2022-02-28 14:18 UTC, merged