Corrige les adresses mails tronquées sur la page d’accueil
BaseAdresseNationale/mes-adresses pull request #504
Opened 2022-03-02 15:34 UTC by GllmR

Actuellement, les adresses mails des administrateurs sont tronquées lorsqu'elles sont trop longues.
Ce problème est dû à l’utilisation du Tooltip Evergreen dont la taille ne peux pas dépasser 240px.

Cette PR propose d’ajouter un style global à la racine du site pour modifier la classe qui empêche la `<div />` de s’agrandir.
J'ai ajouté un commentaire pour préciser le but de ce style global.

Avant : 

![image](https://user-images.githubusercontent.com/56537238/156391221-a95b39f0-ff70-455f-b492-7059f65b07a7.png)

Après : 

![image](https://user-images.githubusercontent.com/56537238/156391585-0713674a-a0b6-4742-9708-f76d3da36e3a.png)

2022-03-03 09:38 UTC, Maxine-Le-Pennec approved these changes

2022-03-03 09:43 UTC, tmerlier requested changes

2022-03-03 09:43 UTC, tmerlier commented on pages/_app.js
> +        div[id^="evergreen-tooltip"].ub-max-w_240px.ub-bg-clr_white.ub-box-szg_border-box {
Le reste n'est pas nécessaire. Sauf s'il empêche de modifier d'autre `tooltip` qu'on ne voit pas ici ?

2022-03-03 11:16 UTC, tmerlier commented on pages/_app.js
> +        div[id^="evergreen-tooltip"].ub-max-w_240px.ub-bg-clr_white.ub-box-szg_border-box {
Ça peut être utile oui. Ça évitera qu'un jour quelqu'un retire les classes en se disant que tout fonctionne sans, comme je viens de le faire.

2022-03-04 08:30 UTC, tmerlier approved these changes

2022-03-04 08:30 UTC, merged