Amélioration de la modification/suppression en masse des numéros
BaseAdresseNationale/mes-adresses pull request #509
Opened 2022-03-07 14:20 UTC by cedric-famibelle-pronzola

resolves #462 

## ⚠️ Liée à la PR mes-adresses-api

2022-03-08 09:50 UTC, tmerlier requested changes

2022-03-08 09:50 UTC, tmerlier commented on components/grouped-actions.js
> +      if (c) {
Évitons les noms de variable cryptique comme celle-ci.

2022-03-08 09:50 UTC, tmerlier commented on components/grouped-actions.js
> +    const getCertifie = c => {
Idem ici pour le nom de variable. Il est même préférable de préfixer le nom par `is` car il me semble que c'est un booléen.

2022-03-08 09:50 UTC, tmerlier commented on components/grouped-actions.js
> +                <Alert intent='warning' marginBottom={8}>Attention, certains numéros sélectionnés possèdent un commentaire. En cas de modification, il sera remplacé.</Alert>
```suggestion
                <Alert intent='warning' marginBottom={8}>Attention, certains numéros sélectionnés possèdent un commentaire. En cas de modification, leurs commentaires seront remplacés.</Alert>
```

2022-03-08 09:50 UTC, tmerlier commented on lib/bal-api/index.js
> +}
Attention il manque la notification indiquant la réussite ou l'échec de la modification.

2022-03-09 10:52 UTC, GllmR reviewed
Si on a modifié un toponyme, il n'est plus possible d’ajouter un toponyme avec la modification multiple.

**Reproduction :**   
Dans une voie,
- Ajouter un toponyme à un numéro et valider
- Retirer le toponyme au même numéro (aucun numéro ne possède de toponyme)
- Ouvrir la sélection multiple : 

![image](https://user-images.githubusercontent.com/56537238/157427136-c56767e3-a9dd-48af-b13a-761586892ff0.png)

_(pourtant le numéro en question ne possède pas de toponyme)_

2022-03-15 08:55 UTC, tmerlier requested changes

2022-03-15 08:55 UTC, tmerlier commented on components/grouped-actions.js
> +          [positionType === '' ? null : 'positionType']: positionType,
La pirouette aurait pu être jolie, quoi que peu lisible mais cette ligne pourrait n'a pas le comportement attendu est peut être égale à `null: null`.

Il ajouter `positionType` à `changes` seulement si ça valeur existe.

2022-03-15 08:55 UTC, tmerlier commented on components/voie/numeros-list.js
>      try {
Ce `try/catch` est désormais sans effet car l'erreur est déjà récupérée dans `removeMultipleNumeros`. Il peut  être supprimé dans le cas présent.

2022-03-15 08:55 UTC, tmerlier commented on components/voie/numeros-list.js
>      try {
Ce `try/catch` est désormais sans effet car l'erreur est déjà récupérée dans `batchNumeros`. Il peut  être supprimé dans le cas présent.

2022-03-15 08:55 UTC, tmerlier commented on components/voie/numeros-list.js
>      try {
Par ailleurs le `toaster.success` est déjà gérer dans `removeMultipleNumeros`, il peut donc aussi être retiré ici.

2022-03-15 08:55 UTC, tmerlier commented on components/voie/numeros-list.js
>      try {
Même chose ici, le `toaster.success` est déjà gérer dans `removeMultipleNumeros`, il peut donc aussi être retiré ici.

2022-03-15 08:55 UTC, tmerlier commented on lib/bal-api/index.js
> +export function batchNumeros(balId, body, token, isToasterDisabled) {
`isToasterDisabled` n'est pas utile. C'est ici que devrait être envoyé les notifications afin de rester homogène avec le reste du code.

2022-03-15 13:41 UTC, cedric-famibelle-pronzola commented on components/grouped-actions.js
> +          [positionType === '' ? null : 'positionType']: positionType,
pas trop compris.
`positionType` est justement ajouté si la valeur existe.
qu'est-ce qu'il faudrait renvoyer si la valeur n'existe pas ?

2022-03-16 08:16 UTC, tmerlier commented on components/grouped-actions.js
> +          [positionType === '' ? null : 'positionType']: positionType,
Avec ce code on peut obtenir par exemple:
```
    changes = {
      voies: '57128kkh223HJ3K2HJ',
      null: null,
      toponyme: '57128kkh223HJ3K2HJ',
      ...
    }
```

2022-03-16 14:28 UTC, tmerlier requested changes

2022-03-16 14:28 UTC, tmerlier commented on components/grouped-actions.js
>      try {
Ce `try/catch` peut être retiré de la même façon que les autres. Et la state `error` par extension.

2022-04-25 12:58 UTC, tmerlier approved these changes

2022-04-26 13:51 UTC, merged