Utiliser des chemins relatifs pour les imports
BaseAdresseNationale/mes-adresses pull request #516
Opened 2022-03-08 14:32 UTC by Maxine-Le-Pennec

Mise à jour du système d'import. 
Utilisation des chemins relatifs pour les imports afin de clarifier la lecture du code.

**### Exemple**
`import foo from ".../.../components/foo.js"` devient `import foo from "@components/foo"`

Close #514

2022-03-08 14:44 UTC, tmerlier requested changes
Au vue de la densité je n'ai pas commenté tous les fichiers mais les commentaires que j'ai laisserai devrait suffisamment d'aider à continuer.

2022-03-08 14:44 UTC, tmerlier commented on components/bal/position-editor.js
>  import InputLabel from '../input-label'
```suggestion
import InputLabel from '@/components/input-label'
```

2022-03-08 14:44 UTC, tmerlier commented on components/bal/toponyme-editor.js
>  import AssistedTextField from '../assisted-text-field'
```suggestion
import AssistedTextField from '@/components/assisted-text-field'
```

2022-03-08 14:44 UTC, tmerlier commented on components/bal/toponymes-list.js
>  import ToponymeEditor from './toponyme-editor'
```suggestion
import TableRow from '@/components/table-row'
import ToponymeEditor from '@/components/bal/toponyme-editor'
```

2022-03-08 14:44 UTC, tmerlier commented on components/bal/voie-editor.js
>  import FormInput from '../form-input'
```suggestion
import Form from '@/components/form'
import FormInput from '@/components/form-input'
```

2022-03-08 14:44 UTC, tmerlier commented on pages/_app.js
> +import Sidebar from '@/components/layout/sidebar'
Il faudrait déplacer `/components/layout` dans `/layouts`.

C'est ce que demande le `jsconfig.json`

2022-03-09 09:54 UTC, tmerlier requested changes

2022-03-09 09:54 UTC, tmerlier commented on layouts/dashboard.js
> +import Header from '../components/header'
```suggestion
import Map from '@/components/dashboard/map'
import Header from '@/components/header'
```

2022-03-09 09:54 UTC, tmerlier commented on pages/_error.js
> +import Custom404 from '@/pages/404'
Il manque un saut de ligne.

2022-03-09 09:54 UTC, tmerlier commented on pages/bal.js
> +import {normalizeSort} from '@/lib/normalize'
Cet import pourrait être regroupé avec les autres `@/lib`

2022-03-09 09:54 UTC, tmerlier commented on pages/dashboard/departement.js
> +import DashboardLayout from '@/layouts/dashboard'
Cet import pourrait être appelé avant ce groupe d'import.

2022-03-09 09:54 UTC, tmerlier commented on pages/_app.js
> +import ErrorPage from '@/pages/_error'
Profitons en pour regrouper les import entre eux.

2022-03-11 14:40 UTC, tmerlier approved these changes

2022-03-14 16:47 UTC, GllmR reviewed
~~Lorsqu'on sélectionne les parcelles d’un numéro, on n'a pas de retour visuel, les parcelles ne deviennent pas vertes ou rouges au survol.~~

_Édit : Le problème est apparemment connu et ne viendrait pas de ces modifications_

2022-03-15 08:36 UTC, tmerlier commented
> Lorsqu'on sélectionne les parcelles d’un numéro, on n'a pas de retour visuel, les parcelles ne deviennent pas vertes ou rouges au survol.

Le problème est malheureusement déjà présent en prod, il n'a pas était introduit par cette PR.

2022-03-15 08:36 UTC, merged