Améliore les performances du dashboard
BaseAdresseNationale/mes-adresses pull request #547
Opened 2022-04-06 06:20 UTC by cedric-famibelle-pronzola

## Liée à la PR [mes-adresses-api #322](https://github.com/BaseAdresseNationale/mes-adresses-api/pull/322)

- Nouvelle route qui liste les BAL sans les BAL de demo
- Amélioration du composant `getBALByStatus`
- Amélioration de la page `dashboard/departement`

2022-04-06 07:56 UTC, tmerlier requested changes
L'ajout de la nouvelle route `/bases-locales/excluded-demo` ne me parait pas être une bonne pratique.
Il serait peut-être préférable de d'ajouter un paramètre pour filtrer des `status` à la requête `/bases-locales/`

2022-04-06 07:56 UTC, tmerlier commented on pages/dashboard.js
> +    layout: 'fullscreen'
Attention, tu as du mal faire un merge ou un rebase de ta branche, car `layout` n'existe plus aujourd'hui.

2022-04-06 09:41 UTC, GllmR commented on pages/dashboard.js
> +    layout: 'fullscreen'
Effectivement, on ne voit pas les données sur la carte : 
![image](https://user-images.githubusercontent.com/56537238/161946585-eaeb92a1-b39d-46ee-b896-218c4dce6a92.png)

2022-04-06 14:21 UTC, tmerlier requested changes
Nous pourrions charger ses pages uniquement côté serveur avec `getServerSideProps `.

2022-04-06 14:21 UTC, tmerlier commented on pages/dashboard/departement.js
> +    layout: 'fullscreen'
Attention `layout` est encore défini ici aussi.

2022-04-25 10:13 UTC, tmerlier requested changes

2022-04-25 10:13 UTC, tmerlier commented on pages/dashboard.js
> +  const {basesLocalesStats, basesLocalesStatsByStatus} = stats
```suggestion
  const {basesLocalesStats, basesLocalesStatsByStatus} = await getBasesLocalesStats()
```

2022-04-25 10:13 UTC, tmerlier commented on pages/dashboard/departement.js
> +  const filteredCommunesInBAL = communesActuelles.filter(({code}) => codesCommunes.includes(code))
Le `sortBy` pourrait être fait ici directement.

2022-04-27 13:21 UTC, tmerlier approved these changes

2022-05-11 12:39 UTC, tmerlier commented
Abandon de ces modifications, jugées non prioritaires et pas assez impactantes.

2022-05-11 12:39 UTC, closed without merging