Ajout decoupage-administratif le plan orthophoto
BaseAdresseNationale/mes-adresses pull request #552
Opened 2022-04-13 13:28 UTC by vinsag

Ticket issue#464 :
- Le découpage administratif est ajouté au plan orthophoto
- J'ai supprimé l'appel à la source découpage-administratif dans les styles vector et plan-ign car les fonds sont déja présent sur la carte.

2022-04-14 16:16 UTC, tmerlier requested changes
Bien que les fonds de carte embarque déjà un certain découpage administratif, il est nécessaire d'utiliser le même partout par souci d'homogénéité.
Cela nécessite donc de cacher les couches déjà présentes, quand il y en a, et d'utiliser https://openmaptiles.geo.data.gouv.fr/data/decoupage-administratif.json.

Attention, il est également nécessaire d'appliquer un style adapté à chaque fond de carte. Si le contour des communes affiché en gris, comme proposé dans cette PR, est satisfaisant pour les fonds vectoriels, cette couleur n'est pas assez contrastée sur la photo aérienne. Des lignes blanches serait certainement plus visible.

2022-04-14 16:16 UTC, tmerlier commented on components/map/styles/plan-ign.json
> -    "url": "https://openmaptiles.geo.data.gouv.fr/data/decoupage-administratif.json"
Il faut laisser cette source.

En revanche, il est nécessaire de cacher les limites déjà présente dans ce fond de carte.

2022-04-14 16:16 UTC, tmerlier commented on components/map/styles/vector.json
> -      "url": "https://openmaptiles.geo.data.gouv.fr/data/decoupage-administratif.json"
Pareil ici, il faut laisser cette source et cacher les limites déjà présente dans le fond de carte.

2022-04-14 16:16 UTC, tmerlier commented on components/map/styles/ortho.json
> +    },
C'est `decoupage-administratif` dont nous avons besoin. `france-vector` n'est pas adapté car très lourd.
```suggestion
    "decoupage-administratif": {
      "type": "vector",
      "url": "https://openmaptiles.geo.data.gouv.fr/data/decoupage-administratif.json"
    },
```

2022-04-22 10:03 UTC, vinsag commented
Fermeture pull request suite probleme merge

2022-04-22 10:03 UTC, closed without merging