Mutualise les states des composants CreateForm et UploadForm
BaseAdresseNationale/mes-adresses pull request #568
Opened 2022-05-09 07:35 UTC by cedric-famibelle-pronzola

- Conditionne l'utilisation des composants `CreateForm` et `UploadForm` en fonction de l'index `const Form = index === 0 ? CreateForm : UploadForm`
- Mise en commun des states des 2 composants

2022-05-09 07:47 UTC, tmerlier requested changes
En plus des `states`, il y a aussi les différentes méthodes comme `onSubmit`, `onCancel`, `reset`, etc qui gagnerait à être mutualisés.

Mais surtout la sélection de la commune, car elle entraine la vérification d'une BAL en doublon chez l'utilisateur. Actuellement, `checkUserBALs` est inutilement doublonné et déclenché différemment alors qu'il pourrait être calculé au moment où la commune est sélectionnée.

2022-08-24 13:19 UTC, tmerlier requested changes
La partie `<AlertPublishedBAL />` devrait être gérée côté composant parent au lieu d'être dupliqué dans chaque formulaire.

2022-08-24 13:19 UTC, tmerlier commented on pages/new.js
> +                defaultCommune={defaultCommune}
`defaultCommune` n'est plus utilisé

2022-08-24 13:19 UTC, tmerlier commented on pages/new.js
> +                onSelect={onSelect}
`onSelect` n'est plus utilisé.

2022-08-24 13:19 UTC, tmerlier commented on pages/new.js
> +  const [selectedCodeCommune, setSelectedCodeCommune] = useState(defaultCommune ? defaultCommune.code : null)
`selectedCodeCommune` n'est pas nécessaire si `selectedCommune` existe. Il suffit de récupérer `selectedCommune.code`.

Là, on se retrouve à maintenir deux states et à les garder synchronisées.

2022-08-24 13:19 UTC, tmerlier commented on components/new/create-form.js
> +  }, [redirectToNewBAL, bal])
C'est dans le composant parent que cette logique doit être géré.

2022-08-24 13:19 UTC, tmerlier commented on components/new/upload-form.js
>      setSelectedCodeCommune(null)
```suggestion
    resetForm()
```

2022-08-24 13:39 UTC, cedric-famibelle-pronzola commented on pages/new.js
> +  const [selectedCodeCommune, setSelectedCodeCommune] = useState(defaultCommune ? defaultCommune.code : null)
Ça pose problème pour le texte de la barre de recherche.

`communes[0]` utilisé dans `UploadForm` n'est pas le même objet que celui récupéré par `getCommune` dans `pages/new`.

Le texte affiché par la recherche (géré par `CommuneSearch`) serait incorrect, car il n'y a pas `commune.departement` dans l'objet `communes[0]` utilisé par `UploadForm`

2022-08-25 09:59 UTC, tmerlier commented on pages/new.js
> +  const [selectedCodeCommune, setSelectedCodeCommune] = useState(defaultCommune ? defaultCommune.code : null)
Je ne comprends pas pourquoi ça gênerait leur cohabitation dans la même state.

2022-08-30 08:42 UTC, cedric-famibelle-pronzola commented
Sera remplacé par une PR permettant de partager entre les formulaires, uniquement le nom de la BAL et l'e-mail de l'utilisateur.

2022-08-30 08:42 UTC, closed without merging