Suppression "Soft"
BaseAdresseNationale/mes-adresses pull request #628
Opened 2022-06-27 07:01 UTC by GllmR

## Contexte : 

Actuellement, lorsqu’un utilisateur supprime une BAL, celle-ci est supprimée définitivement, sans moyens d’annuler son action.

## Solution :

2022-06-27 12:30 UTC, cedric-famibelle-pronzola requested changes
Sur la page /all les BALs ne sont pas consultables
C'est un comportement voulu ? Parce qu'on peut y accéder par l'url `/bal/:IdBal`

2022-06-27 12:30 UTC, cedric-famibelle-pronzola commented on lib/bal-api/index.js
> +  return fetchDeleted ? allBAL : allBAL.filter(bal => !bal._deleted)
`fetchDeleted` est `true` avec l'appel `await listBasesLocales({fetchDeleted: false})`
Il manque les accolades ou il faudrait que la méthode soit différente :
```js
export async function listBasesLocales(fetchDeleted = false) {
  const allBAL = await request('/bases-locales')

  return fetchDeleted ? allBAL : allBAL.filter(bal => !bal._deleted)
}
```

avec l'appel `await listBasesLocales(true)`

2022-06-29 14:00 UTC, tmerlier requested changes
On a fait quelques étapes en trop ici.

Pour le moment on part sur une première itération sans modification pour l'utilisateur.
Donc une BAL supprimée renvoi une page 404 et l'API renvoi uniquement les BAL qui ne sont pas supprimée.

On aura l'opportunité de profiter de cette amélioration dans une prochaine itération.

2022-07-04 10:10 UTC, tmerlier requested changes
Pour rappel, l'objectif de cette PR, c'est : "Zéro changement pour l'utilisateur".

2022-07-04 10:10 UTC, tmerlier commented on components/user-bases-locales.js
> +      const findedBasesLocales = basesLocales.filter(bal => Boolean(bal) && !bal._deleted)
Ce filtre ne devrait pas être nécessaire ici , car il devrait se trouver au niveau de l'appel à l'API pour justement empêcher la récupérer de BAL supprimée.

2022-07-04 10:10 UTC, tmerlier commented on components/voie/numeros-list.js
> +  const {baseLocale, isEditing, reloadNumeros, reloadGeojson, toponymes, refreshBALSync, isDeleted} = useContext(BalDataContext)
`isDeleted` n'existe plus.

2022-07-04 10:10 UTC, tmerlier commented on components/voie/voie-heading.js
> +  const {editingId, isEditing, numeros, isDeleted} = useContext(BalDataContext)
`isDeleted` n'existe plus.

2022-07-04 10:10 UTC, tmerlier commented on lib/bal-api/index.js
> +export async function searchBAL(codeCommune, userEmail, fetchDeleted) {
Inutile d'ajouter `fetchDeleted`, pour le moment on filtre automatique les BAL supprimées.

2022-07-04 14:11 UTC, tmerlier approved these changes

2022-07-04 14:35 UTC, cedric-famibelle-pronzola approved these changes

2022-08-30 08:02 UTC, merged