Maxine/langues regionales
BaseAdresseNationale/mes-adresses pull request #631
Opened 2022-07-12 14:38 UTC by Maxine-Le-Pennec

Cette PR fait suite au ticket suivant : **Ajouter des champs texte alternatifs pour les langues régionales [#625](https://github.com/BaseAdresseNationale/mes-adresses/issues/625)**

La section "Nom" des formulaires d’édition des voies et des toponymes propose à présent un bouton `Ajouter une langue régionale` permettant d'ajouter un champ texte supplémentaire afin d'indiquer une alternative du nom. 

Ce nouveau champ texte est accompagné : 
- d’un sélecteur pour indiquer la langue régionale utilisée pour cette alternative ([Liste des langues supportées](https://github.com/BaseAdresseNationale/mes-adresses/issues/128))
- d’un bouton "corbeille" permettant de supprimer le champ
- du bouton "assistance à la saisie des accents"

Si le formulaire est validé alors qu'un champ "nom alternatif" est vide, alors le formulaire ignore cette langues régionales.

### **VOIES**
<img width="499" alt="Capture d’écran 2022-07-11 à 16 14 39" src="https://user-images.githubusercontent.com/66621960/178294715-97e333d3-423b-42b9-b1e8-d75eaee65a98.png">
<img width="501" alt="Capture d’écran 2022-07-11 à 16 46 09" src="https://user-images.githubusercontent.com/66621960/178294720-5658f372-b8d6-4886-9b48-4084bc6de750.png">
<img width="502" alt="Capture d’écran 2022-07-11 à 16 46 36" src="https://user-images.githubusercontent.com/66621960/178294721-1d6b1fca-8585-4df7-976b-a80126e690b1.png">

---------------------------------------

### **TOPONYMES**
<img width="501" alt="Capture d’écran 2022-07-11 à 16 53 02" src="https://user-images.githubusercontent.com/66621960/178294722-83573684-a9b9-418f-b994-cbdf1d7ee1ee.png">
<img width="498" alt="Capture d’écran 2022-07-11 à 16 53 20" src="https://user-images.githubusercontent.com/66621960/178294724-ff9e8762-0af2-4951-9a36-8a920bb0a345.png">

2022-07-13 14:46 UTC, cedric-famibelle-pronzola requested changes
En sélectionnant une langue, le sélecteur reste ouvert.

Après avoir cliqué sur "Ajouter une langue régionale", on peut enregistrer après avoir rempli le champ, sans avoir sélectionné de langue.

2022-07-13 14:46 UTC, cedric-famibelle-pronzola commented on components/bal/language-field.js
> +
```suggestion 
  const handlePlaceholder = `Nom ${isToponyme ? 'du toponyme' : 'de la voie'} en ${field.label === '' && field.value ? `${detectLanguage(field).toLowerCase()}` : 'langue régionale'}`
```

J'aurais quand même tendance à privilégier un if ou une fonction

2022-07-15 15:32 UTC, Maxine-Le-Pennec commented
> Lorsque l’on sélectionne une langue, il faudrait que le panneau se ferme automatiquement.
> 
Corrigé dans le commit [af00546](https://github.com/BaseAdresseNationale/mes-adresses/pull/631/commits/af0054655c4f35b8be64fba332238d9bb2011fcf)

> Les noms de voies en langues régionales n’appariassent pas dans l’onglet "toponymes"
> 
> Avec le "ajouter une adresse", il n’est pas possible d’ajouter un nom de voie alternatif.
> 
> Dans "numéros", il n’est pas possible d'ajouter un nom de voie alternatif lors de la création d’une nouvelle voie.
> 
> La taille des textes a augmentée -> Je ne pense pas que ce soit la bonne PR pour le faire et :
> 
La taille augmente afin d'obtenir un design harmonieux avec l'ajout des noms alternatifs.

> 
> ![image](https://user-images.githubusercontent.com/56537238/179252067-769f8bc8-3bf2-4960-8b06-48d5d38e4e9e.png)
Corrigé dans le commit [bd2d110](https://github.com/BaseAdresseNationale/mes-adresses/pull/631/commits/bd2d1101078cc29531769fa855d88f193d589096)

2022-07-18 20:14 UTC, tmerlier requested changes

2022-07-18 20:14 UTC, tmerlier commented on components/bal/voie-editor.js
> +          </Button>
Cette méthode permet de rajouter une infinité de langues régionales, il est préférable de limiter au nombre max de langues supportées.

2022-07-18 20:14 UTC, tmerlier commented on components/bal/numero-editor/numero-voie-selector.js
> +                </Button>
La gestion des langues régionales n'est pas nécessaire ici. Toutes les modifications de ce fichier peuvent être revert.

2022-07-18 20:14 UTC, tmerlier commented on components/bal/numero-editor.js
> +              onRemoveLanguage={removeLanguage}
La gestion des langues régionales n'est pas nécessaire ici. Toutes les modifications de ce fichier peuvent être revert.

2022-07-18 20:14 UTC, tmerlier commented on components/bal/toponyme-editor.js
> +import LanguageField from './language-field'
```suggestion
import LanguageField from '@/components/bal/language-field'
```

2022-07-18 20:14 UTC, tmerlier commented on components/bal/toponyme-editor.js
> +          </Button>
Ce code est celui se trouvant sur `voie-editor` est strictement identique. Nous pourrions faire un composant qui s'occuperait intégralement de la gestion des langues régionales. Celui-ci remplacerait également le `/hooks/languages.js` qui ne peut pas être implémenté en l'état.

Il retournerait le `nomAlt` à son composant parent grâce à un `setState`.

2022-07-19 07:48 UTC, Maxine-Le-Pennec commented on components/bal/language-field.js
> +        <Button
Parce que c'est un peu plus compliqué de rajouter des icônes sur le selecteur d'Evergreen
Selon la doc et leur [exemple](https://codesandbox.io/s/e067lg), il faut que l'icône soit une url redirigeant vers une image. J'ai donc laissé ça de côté pour le moment.

2022-07-19 07:53 UTC, Maxine-Le-Pennec commented on components/voie/voie-heading.js
> +  ) : (
J'ai réorganisé l'emplacement des éléments pour obtenir un design permettant un affichage harmonieux des langues régionales. J'ai suivi la logique de la maquette.

2022-07-19 07:55 UTC, Maxine-Le-Pennec commented on components/assisted-text-field.js
> +        width={isFullWidth ? '100%' : ''}
Après plusieurs essais, je trouvais justement que c'était l'inverse qui faisait bizarre. Mais je vais restaurer cette partie :)

2022-07-19 08:11 UTC, Maxine-Le-Pennec commented on components/toponyme/toponyme-heading.js
> +  ) : (
J'ai réorganisé l'emplacement des éléments pour obtenir un design permettant un affichage harmonieux des langues régionales. J'ai suivi la logique de la maquette.

2022-07-19 12:18 UTC, tmerlier requested changes

2022-07-19 12:18 UTC, tmerlier commented on components/bal/voie-editor.js
> +            disabled={selectedLanguages.length === 7}
Il faudrait se baser sur le nombre de langues supportées et non un chiffre en dur.
La liste des langues devrait être définie quelque part afin de pouvoir être appelé partout, de cette façon, on s'assure de toujours avoir le même référentiel et de pouvoir le faire évoluer facilement.

2022-07-19 13:58 UTC, GllmR approved these changes

2022-07-19 13:58 UTC, cedric-famibelle-pronzola approved these changes

2022-07-19 14:14 UTC, Maxine-Le-Pennec commented on components/bal/language-field.js
> +          isFocus
Problème en résolution dans la PR  [Mauvaise gestion du focus dans le composant <AssistedTextField/>](#634)
Cette solution permet de ne pas passer la prop isFocus au AssistedTextField sans déclencher une erreur.

2022-07-21 10:39 UTC, jdesboeufs requested changes

2022-07-21 10:39 UTC, jdesboeufs commented on package.json
> +    "flags": "node scripts/available-flags",
build-available-flags
node scripts/build-available-flags

2022-07-21 10:39 UTC, jdesboeufs commented on scripts/available-flags.js
> +const fs = require('fs-extra')
chmod 755 + en-tête `#!/usr/bin/env Node`

2022-07-21 10:39 UTC, jdesboeufs commented on package.json
> +    "flags": "node scripts/available-flags",
Je suggère de le mettre dans le build, et de créer un `build-next = next build`
`build = yarn build-available-flags && yarn build-next`

2022-07-21 14:49 UTC, jdesboeufs approved these changes

2022-07-21 14:52 UTC, tmerlier approved these changes

2022-07-21 14:52 UTC, merged