Corrige le problème de mise en évidence des parcelles sélectionnées
BaseAdresseNationale/mes-adresses pull request #639
Opened 2022-07-26 17:05 UTC by cedric-famibelle-pronzola

Resolves #573

Après la modification des parcelles d'une adresse, on charge à nouveau les parcelles de la BAL.

2022-07-27 10:31 UTC, IGNFBourcier commented on components/bal/numero-editor.js
> +      if (!isEqual(initialValue?.parcelles, body.parcelles)) {
efficace et fonctionnant dans la majorité des cas.
isEqual tient compte de l'ordre, donc dans de rares cas peut forcer un reload.

j'avais pensé à un xor à la place de difference. Mais plus couteux en ressource qu'un isequal sur les grosses listes.

2022-07-28 15:56 UTC, tmerlier requested changes
Le problème est toujours là pour moi.

2022-07-28 15:58 UTC, cedric-famibelle-pronzola commented
> Le problème est toujours là pour moi.

Lequel ? Le scenarii 1 que @IGNFBourcier à noté ou le 2 ? https://github.com/BaseAdresseNationale/mes-adresses/issues/573#issuecomment-1172557163

2022-08-05 14:59 UTC, tmerlier approved these changes

2022-08-08 13:36 UTC, GllmR reviewed
- [ ] À la création d’une BAL, la carte se centre au bon endroit, mais les adresses ne sont pas affichées
- [ ]  Lorsque l’on souhaite éditer un numéro depuis la carte (cliquer sur un numéro de la carte), dans l’onglet toponyme, le numéro disparaît, on passe en mode "édition" mais l’éditeur ne s’ouvre pas.
- [ ]  Le 'mouse-out' ne fonctionne pas pour la liste des parcelles dans l’éditeur (la dernière parcelle survolée reste rouge)
- [ ]  Les labels "nom de voie" sont derrière les points des positions : 
![image](https://user-images.githubusercontent.com/56537238/183427412-cdac6854-a10c-4fb4-b342-994570464d80.png)

2022-08-09 07:15 UTC, IGNFBourcier commented
- A la suppression d'un numéros de la voie conteant une parcelle, la parcelle reste colorée sur la carte. (liste parcelle non rechargée)
- Lorsque l'on clique sur un numero au niveau de carte pour l'éditer, si celui-ci se trouve au niveau d'une de ses parcelles celle-ci est deselectionner à l'ouverture du formulaire

2022-08-09 15:17 UTC, merged