Amélioration du système de focus
BaseAdresseNationale/mes-adresses pull request #648
Opened 2022-08-01 09:12 UTC by Maxine-Le-Pennec

Le système de gestion de focus était obsolète. Nous utilisions un custom hook pour gérer les `ref` et ainsi, le focus sur les inputs.

Cette PR remplace le système mis en place par custom hook `useFocus` et exploite le hook `useRef` proposé par React, plus adapté. 
La refonte de la gestion du focus permet aussi de corriger le souci de retour du curseur à la fin du champ et non à sa position lorsqu'un caractère spécial est rajouté par l'outil d'accents.

Close #647 #646

2022-08-02 07:24 UTC, tmerlier requested changes

2022-08-02 07:24 UTC, tmerlier commented on hooks/focus.js
> +function useFocus({value, isFocus}) {
Ce hook s'appelle `useFocus`, on s'attend à ce qu'il fasse toujours le focus. Le rendre optionnel n'est pas nécessaire je pense.

2022-08-02 07:24 UTC, tmerlier commented on hooks/caret-position.js
> +  const [end, setEnd] = useState(value.current ? value.current.length : 0)
`value` n'est pas utile, car sa valeur ne sera utilisée que pour l'initialisation de `start` et `end`. Ce qui est passé en valeur par défaut à `useState` est en effet attribué qu'une seule fois au premier cycle de vie du composant.

```suggestion
  const [start, setStart] = useState(initialValue?.current.length || 0)
  const [end, setEnd] = useState(initialValue?.current.length || 0)
```

2022-08-02 07:24 UTC, tmerlier commented on hooks/focus.js
> +function useFocus({value, isFocus}) {
Y a-t-il vraiment des cas où il est possible de donner une valeur à `value` ? Sinon il n'est pas nécessaire d'attendre cette props.

2022-08-02 07:24 UTC, tmerlier commented on hooks/caret-position.js
> +  const [focusedElement] = useFocus({value: null, isFocus})
Pourquoi ne pas passer `initialValue` ici ?
```suggestion
  const [focusedElement] = useFocus({value: initialValue, isFocus})
```

2022-08-02 07:24 UTC, tmerlier commented on hooks/caret-position.js
> +  const [end, setEnd] = useState(value.current ? value.current.length : 0)
Il n'est pas nécessaire de créer deux states. Les deux étant dépendantes l'une de l'autre au moment de la mise à jour, nous pouvons les regrouper.

```suggestion
  const initialCursorPos = value.current ? value.current.length : 0
  const [cursorPos, setCursorPos] = useState({start: initialCursorPos, end: initialCursorPos})
```

2022-08-02 07:24 UTC, tmerlier commented on hooks/caret-position.js
> +    if (focusedElement && focusedElement.current) {
Cette condition ne devrait pas être nécessaire, je ne vois pas de cas où elle pourrait être appelé sans que `focusedElement` soit initialisé.

2022-08-02 07:24 UTC, tmerlier commented on components/new/demo-form.js
> +  const [ref, setRef] = useState()
`useFocus` ne fait pas le job ?

2022-08-02 08:11 UTC, Maxine-Le-Pennec commented on hooks/focus.js
> +function useFocus({value, isFocus}) {
Les champs tels que les langues régionales n'ont pas le focus à l'ouverture du formulaire mais ont quand même besoin d'une gestion du focus lorsqu'on ajoute des accents avec le bouton

2022-08-02 08:26 UTC, Maxine-Le-Pennec commented on components/new/demo-form.js
> +  const [ref, setRef] = useState()
Si j'utilise` useFocus`, le focus fonctionne ,mais lorsque la section d'autocomplete s'ouvre, elle est décalée. Je n'ai pas trouvé de meilleure solution à ce jour.

2022-08-02 10:14 UTC, tmerlier requested changes
Pas fan de la gestion actuel du focus par `useFocus`. Je te propose de faire :
```
import {useState, useRef, useEffect} from 'react'

function useFocus({autofocus = false}) {
  const [ref, setRef] = useRef()
  const [isFocus, setIsFocus] = useState(autofocus)

  useEffect(() => {
    if (ref?.current && isFocus) {
      ref.current.focus()
    }
  }, [ref, isFocus])

  return [setRef, setIsFocus]
}

export default useFocus
```

De cette façon tu peux avoir un focus par défaut et gérer ensuite les changements de focus `const [isFocus, setIsFocus] = useFocus(autofocus: true/false)`

2022-08-02 10:14 UTC, tmerlier commented on components/demo-warning.js
> +        onOpenComplete={() => focusedElement.current.focus()}
Le hook `useFocus` ne semble pas utile ici puisqu'on refait un `focus` manuellement.

2022-08-02 10:14 UTC, tmerlier commented on hooks/focus.js
> +function useFocus({value, isFocus}) {
Dans ce cas le hook `useFocus` ne semble pas très utile puisque qu'on en revient à utiliser une state `isFocus` et de faire ensuite le focus à la main. Autant simplement utiliser `useRef` et garder `useFocus` uniquement pour du focus automatique.

2022-08-02 10:19 UTC, Maxine-Le-Pennec commented on hooks/focus.js
> +function useFocus({value, isFocus}) {
Le problème c'est que ça ne fonctionne pas en utilisant `useRef` non plus. On avait essayé moults solution pour ce composant et aucune ne semblait fonctionner à par utiliser `useSate`

2022-08-04 07:46 UTC, tmerlier requested changes

2022-08-04 07:46 UTC, tmerlier commented on hooks/caret-position.js
> +  }, [caretPosition, isFocus, ref])
Si `isFocus` est vraiment nécessaire, alors un petit commentaire est le bienvenu.

2022-08-04 07:46 UTC, tmerlier commented on hooks/focus.js
> +function useFocus({autofocus = false}) {
Il n'y qu'une seule prop, il n'est peut-être nécessaire d'envoyer un objet.

```suggestion
function useFocus(autofocus = false) {
```

2022-08-04 07:46 UTC, tmerlier commented on components/langues-regionales-form/language-field.js
> +  const [ref, isFocus, setIsFocus] = useFocus({})
```suggestion
  const [ref, isFocus, setIsFocus] = useFocus({autofocus: false)) 
```

OU

```suggestion
  const [ref, isFocus, setIsFocus] = useFocus() 
```

2022-08-04 07:46 UTC, tmerlier commented on components/demo-warning.js
> +  const [ref, , setIsFocus] = useFocus({})
Même remarque pour l'initialisation.

2022-08-05 14:26 UTC, tmerlier approved these changes

2022-08-05 14:26 UTC, tmerlier commented on components/assisted-text-field.js
> +  exitFocus: () => {}
Pas fan de la solution "function inutile". Nous pourrions rendre `exitFocus` obligatoire puisqu'il y a toujours un `useFocus` à l'origine de la `ref`.

2022-08-05 15:00 UTC, merged