Ajout de la déclaration d'accessibilité
BaseAdresseNationale/mes-adresses pull request #652
Opened 2022-08-01 15:03 UTC by Maxine-Le-Pennec

Une nouvelle page contenant la déclaration d'accessibilité a été ajoutée.
Sa présence est obligatoire.

Un point d'entrée vers cette page est également ajouté dans le header

![Movavi ScreenShot 016 - mes-adresses data gouv fr - localhost](https://user-images.githubusercontent.com/66621960/182179658-41470073-c184-43ee-98ad-b2cc1c9f3e05.jpg)

2022-08-02 08:46 UTC, cedric-famibelle-pronzola requested changes
Je serais d'avis de privilégier le Français pour la nouvelle page : `accessibility` => `accessibilite`

2022-08-02 08:46 UTC, cedric-famibelle-pronzola commented on pages/accessibility.js
> +            <ListItem>Contacter <Strong>le délégué du Défenseur des droits</Strong> dans votre région.</ListItem>
- L68 devrait renvoyer vers https://formulaire.defenseurdesdroits.fr
- L69 devrait renvoyer vers https://www.defenseurdesdroits.fr/saisir/delegues

2022-08-02 09:02 UTC, Maxine-Le-Pennec commented
> Je serais d'avis de privilégier le Français pour la nouvelle page : `accessibility` => `accessibilite`

Je suis d'accord mais toutes les pages sont indiquées en anglais. Dans l'URL, elles sont en anglais aussi.
Je pense qu'il faudrait faire comme sur adresse.data et modifier le nom de la page dans l'url

2022-08-02 09:54 UTC, cedric-famibelle-pronzola commented
> > Je serais d'avis de privilégier le Français pour la nouvelle page : `accessibility` => `accessibilite`
> 
> Je suis d'accord mais toutes les pages sont indiquées en anglais. Dans l'URL, elles sont en anglais aussi. Je pense qu'il faudrait faire comme sur adresse.data et modifier le nom de la page dans l'url

effectivement certaines pages sont en Anglais
changer juste en modifiant le nom du fichier devrait suffire, plutôt que de passer par le server

2022-08-02 13:13 UTC, tmerlier requested changes

2022-08-02 13:23 UTC, Maxine-Le-Pennec commented on components/header.js
> +        </Button>
Le footer n'est visible que sur la page d'accueil, or : 
`Pour les sites internet, la déclaration d’accessibilité est publiée sur le site internet concerné. Elle est mise à disposition au sein d’une page accessibilité, directement accessible depuis la page d’accueil et depuis n’importe quelle page du site.`

cf [Publication de la déclaration d’accessibilité](https://design.numerique.gouv.fr/accessibilite-numerique/declaration-accessibilite/)

2022-08-02 13:41 UTC, cedric-famibelle-pronzola requested changes

2022-08-02 13:41 UTC, cedric-famibelle-pronzola commented on components/header.js
> +          <Link href='/accessibility' textDecoration='none' color='neutral'>
```suggestion
          <Link href='/accessibilite' textDecoration='none' color='neutral'>
```

2022-08-02 14:24 UTC, Maxine-Le-Pennec commented on components/header.js
> +          <Link href='/accessibility' textDecoration='none' color='neutral'>
Bien vu

2022-08-02 14:30 UTC, cedric-famibelle-pronzola approved these changes

2022-08-04 07:37 UTC, tmerlier commented on components/header.js
> +        </Button>
Ok alors, il va falloir faire quelque chose de plus discret que ça.

2022-08-08 10:01 UTC, tmerlier requested changes

2022-08-08 10:01 UTC, tmerlier commented on components/footer.js
> +  icon: ManualIcon,
Rendons le obligatoire, ça n'a pas vraiment de sens de mettre cette icône par défaut.

2022-08-08 10:03 UTC, tmerlier reviewed
Ce n'est pas non plus un lien de documentation (en référence au nom du composant `DocumentationLink`.

Renommons ce composant pour quelque chose de plus générique.

2022-08-09 15:27 UTC, tmerlier approved these changes

2022-08-09 15:29 UTC, merged