Corrige la "div fantôme" des marqueurs de la carte
BaseAdresseNationale/mes-adresses pull request #664
Opened 2022-08-10 15:03 UTC by GllmR

### Problème : 
Lorsque l’on déplace un marqueur, il était possible de "l’attraper" par une partie invisible en dessous à droite de celui-ci.

### Correction : 
La propriété `translate` a été enlevée et remplacée par la propriété `offset` du marqueur react-map-gl

![Capture d’écran 2022-08-10 à 16 57 30](https://user-images.githubusercontent.com/56537238/183937474-ecd4e6c7-e2d5-49bf-835a-250d1e0c4e37.png)

![Capture d’écran 2022-08-10 à 16 57 01](https://user-images.githubusercontent.com/56537238/183937437-7c4da240-9996-4456-b65c-0ecb5d5230ee.png)

Fix #660

2022-08-10 16:05 UTC, Maxine-Le-Pennec approved these changes

2022-08-12 09:58 UTC, tmerlier commented on components/map/editable-marker.js
> +        offsetLeft={-11.225}
La valeur de la mort qui tue.

2022-08-12 09:59 UTC, tmerlier requested changes

2022-08-12 09:59 UTC, tmerlier commented on components/map/editable-marker.js
> +            transform='translate(-30%)'
Le libellé n'est pas parfaitement centré par rapport au marqueur.

![Capture d’écran 2022-08-12 à 11 57 27](https://user-images.githubusercontent.com/7040549/184331641-edccc1c2-7fde-420d-861b-e3ebe240852b.png)

2022-08-12 10:03 UTC, tmerlier commented on components/map/editable-marker.js
> +            transform='translate(-30%)'
Attention, j'imagine que ça doit dépendre de la longueur du libellé.

2022-08-12 10:34 UTC, IGNFBourcier requested changes

2022-08-12 14:28 UTC, tmerlier commented
On a un léger décalage entre la pointe du marqueur point qui indique la position (j'ai rendu la div un peu plus transparente pour mieux voir).

![Capture d’écran 2022-08-12 à 16 26 13](https://user-images.githubusercontent.com/7040549/184374824-f15b3bdc-3681-4f99-bddb-ba9cedc7b1a5.png)
![Capture d’écran 2022-08-12 à 16 26 20](https://user-images.githubusercontent.com/7040549/184374832-85be52f9-e0de-41f9-b94e-dab48ad2bf02.png)

2022-08-16 14:10 UTC, tmerlier approved these changes

2022-08-16 14:10 UTC, merged