Corrige le problème d’affichage des parcelles dans l’éditeur de numéro
BaseAdresseNationale/mes-adresses pull request #673
Opened 2022-08-23 09:15 UTC by GllmR

Lors du survol d’un badge de parcelle dans l’éditeur de numéro, l’agrandissement de la taille du badge créait un clignotement et/ou un décalage perturbant pour l’utilisateur.

Ce comportement n’est pas présent sous MacOs.

Cette Pr propose d’augmenter légèrement la taille de la police de caractère afin d’éviter le clignotement.

### Captures : 

#### Avant :

![capture_bug_parcelle](https://user-images.githubusercontent.com/56537238/186120297-303917b9-c412-4f52-b929-0699f50cb0da.gif)

#### Après : 

![capture_correction_parcelle](https://user-images.githubusercontent.com/56537238/186120350-4f36f2db-f23d-404f-9647-edeaa752f4e5.gif)

Fix #661

2022-08-23 09:28 UTC, cedric-famibelle-pronzola approved these changes

2022-08-23 09:31 UTC, tmerlier commented
Utiliser une `grid` qui imposerait des contraintes serait une solution plus parraine. En changeant juste la taille de la police, le problème se reproduirait si le nombre de caractères change ou que l'interface évolue.

2022-08-23 09:33 UTC, tmerlier requested changes

2022-08-23 09:33 UTC, tmerlier commented on components/bal/numero-editor/select-parcelles.js
> +                fontSize={12}
Quick fix mais ce problème n'étant pas nécessairement une urgence, nous pouvons prendre le temps faire une correction plus solide.

2022-08-24 11:27 UTC, tmerlier approved these changes

2022-08-24 12:33 UTC, merged