Mise en commun des informations du formulaire de création de BAL
BaseAdresseNationale/mes-adresses pull request #689
Opened 2022-09-02 14:36 UTC by cedric-famibelle-pronzola

Les champs _Nom de la BAL_ et _Adresse email_ ne sont plus réinitialisés au changement d'onglet lors de la création d'une BAL.

[Capture vidéo 2022-09-02 18:19:51.webm](https://user-images.githubusercontent.com/45098730/188170034-2f44b6b6-d170-4497-9dd9-a822617966c2.webm)

2022-09-05 09:03 UTC, tmerlier requested changes

2022-09-05 09:03 UTC, tmerlier commented on components/new/upload-form.js
> +}
Ces deux champs sont requis.

2022-09-05 09:03 UTC, tmerlier commented on components/new/create-form.js
> +  email: null
Ces trois champs sont requis.

2022-09-05 09:14 UTC, cedric-famibelle-pronzola commented on components/new/create-form.js
> +  email: null
effectivement `nom` et `email` sont requis, par contre `defaultCommune` ne l'est pas. S'il n'y a pas de `query` de commune, `defaultCommune` est `null`

2022-09-05 14:58 UTC, tmerlier commented on components/new/create-form.js
> +  email: null
`null` est une valeur. Ne sont pas requis les champs qui peuvent être `undefined`. Ici on envoi forcément une valeur donc le champ est requis.

La distinction est importante, car si une `props` vaut `null` alors elle n'aura jamais la valeur par défaut qu'on lui défini. Pour attribuer cette valeur par défaut, la `props` ne doit pas être défini du tout.

2022-09-06 07:40 UTC, tmerlier commented on components/new/create-form.js
> +  email: null
C'est une mauvaise compréhension de `propTypes` malheureusement. Comme un exemple vaut mille mots…

**Composant**
```
import PropTypes from 'prop-types'

const Foo = ({bar}) => (
  <div>{bar}</div>
)

Foo.defaultProps = {
  bar: 'default'
}

Foo.propTypes = {
  bar: PropTypes.string,
}

export default Foo
```

*Rendus*
`<Foo bar="test" />` => `"test"`
`<Foo bar="" />` => `""`
`<Foo bar={null} />` => `null`
`<Foo  />` => `"default"`
`<Foo bar={undefined}  />` => `"default"`


Ici `defaultCommune` a bien une valeur… `null`

2022-09-06 07:56 UTC, cedric-famibelle-pronzola commented on components/new/create-form.js
> +  email: null
Quand je mets `defaultCommune` required j'ai un message d'erreur dans la console : 

![Capture d’écran du 2022-09-06 11-55-17](https://user-images.githubusercontent.com/45098730/188578906-7542d262-26e2-4250-8e5e-0b0cb9c96810.png)

2022-09-06 08:13 UTC, tmerlier commented on components/new/create-form.js
> +  email: null
Hum… Les règles du jeu ont dû changer lors d'une mise à jour j'imagine.
L'exemple au-dessus est toujours, mais et j'imagine que ce warning est là justement pour éviter ce genre de cas.

C'est bon pour moi du coup 👍🏻

2022-09-06 08:39 UTC, tmerlier approved these changes

2022-09-06 08:39 UTC, merged