Modification du `bounds` lorsque plusieurs type de position sont présents
BaseAdresseNationale/mes-adresses pull request #690
Opened 2022-09-02 15:23 UTC by GllmR

## ⚠️ Ne pas merger avant [cette PR](https://github.com/BaseAdresseNationale/mes-adresses-api/pull/357) ⚠️

Cette PR propose de modifier le `bounds` de la carte lorsqu’une position possède plusieurs types.

### Captures : 

![image](https://user-images.githubusercontent.com/56537238/188181886-7f33762f-48aa-4747-9dfe-2c08010d0180.png)

![image](https://user-images.githubusercontent.com/56537238/188181946-2d03f665-ee95-4bfa-81ae-aa8277e3c867.png)

Fix #665

2022-09-05 09:07 UTC, tmerlier commented on components/map/hooks/bounds.js
> +        })
```suggestion
    const features = editedNumero.positions.map((p, idx) => {
      return {
        type: 'Feature',
        geometry: editedNumero.positions[idx].point,
        properties: {id: editedNumero._id}
      }
    })
```

2022-09-05 09:10 UTC, tmerlier requested changes

2022-09-05 09:10 UTC, tmerlier commented on components/map/map.js
> +  }, [numeros, editingId])
Il serait préférable de récupérer l'objet en cours d'édition peu importe ce qu'il est et de l'envoi à `useBounds`.

Le hook pourrait ensuite, si c'est un objet en cours d'édition lui est passé, extraire les positions si celui en a.

2022-09-06 15:23 UTC, cedric-famibelle-pronzola commented on contexts/bal-data.js
> +      return union(voies, toponymes, numeros).find(({_id}) => _id === editingId) || null
Pourquoi ce changement ?

2022-09-07 08:43 UTC, GllmR commented on contexts/bal-data.js
> +      return union(voies, toponymes, numeros).find(({_id}) => _id === editingId) || null
Ça nous permet de récupérer le `editingItem` même lorsqu’il n’y a pas `voies` ou `toponymes` et donc de pouvoir gérer l’édition dans le "header" de la liste des numéros ou dans toponyme.

2022-09-07 08:47 UTC, tmerlier requested changes

2022-09-07 08:47 UTC, tmerlier commented on components/map/hooks/bounds.js
> +        const features = editingItem.positions.map((p, idx) => {
`values` serait plus adapté que `map` dans ce cas.

2022-09-07 10:01 UTC, tmerlier requested changes

2022-09-07 12:03 UTC, GllmR commented on contexts/bal-data.js
> +      return union(voies, toponymes, numeros).find(({_id}) => _id === editingId) || null
Je ne pense pas qu’il soit nécessaire non plus, puisqu’il devrait toujours y avoir un résultat. Je l’ai ajouté par "sécurité".

Je viens de vérifier, lorsque `find` ne trouve rien, il renvoie `undefined`

2022-09-07 12:08 UTC, tmerlier commented on contexts/bal-data.js
> +      return union(voies, toponymes, numeros).find(({_id}) => _id === editingId) || null
Dans notre cas, `null` ou `undefined` revient au même dans tous les cas.

2022-09-13 08:17 UTC, tmerlier approved these changes

2022-09-13 08:21 UTC, merged