Remplissage automatique du champ BAL à la sélection de la commune
BaseAdresseNationale/mes-adresses pull request #694
Opened 2022-09-06 12:30 UTC by cedric-famibelle-pronzola

Resolves #608 
Resolves #615

- Le champ Commune est déplacé vers le haut du formulaire
- Le champ Nom de la Base Adresse Locale est rempli à la sélection de la commune : Adresse de 'commune sélectionnée' 

[Capture vidéo 2022-09-06 16:28:50.webm](https://user-images.githubusercontent.com/45098730/188635513-b8291c09-7ea2-4641-8d61-e390f534596a.webm)

edit : *09/09*
- Amélioration du remplissage automatique 
- Focus automatique sur la barre de recherche

2022-09-07 09:17 UTC, tmerlier requested changes
Le nom de la BAL est reset si jamais on rechange la commune, ce qui veut dire que si l'utilisateur renseigne ce champ, on écrase le nom qu'il a choisi.
Même si ce cas reste rare, je pense que c'est préférable de bloquer le choix de l'utilisateur si celui-ci est différent de `Adresses de {nomCommune}`.

Le champ devrait être pré-rempli aussi au dépôt d'un fichier CSV

2022-09-07 09:56 UTC, GllmR requested changes
Le focus se fait toujours sur la partie "Nom de la BAL" qui a été descendue, ce serait peut-être mieux de remonter le focus sur le nom de la commune ?

2022-09-13 09:26 UTC, GllmR approved these changes

2022-09-21 16:12 UTC, cedric-famibelle-pronzola reviewed
Quand on upload une BAL, au lieu d'avoir le nom du département (dans l'onglet `Créer`) il est systématiquement indiqué (Collectivité d’Outre-Mer)

[Capture vidéo 2022-09-21 20:06:55.webm](https://user-images.githubusercontent.com/45098730/191555906-e2d33811-2687-4895-84a6-8025711c5adc.webm)

2022-09-22 15:43 UTC, tmerlier commented
> Quand on upload une BAL, au lieu d'avoir le nom du département (dans l'onglet `Créer`) il est systématiquement indiqué (Collectivité d’Outre-Mer)
> 
>  Capture.video.2022-09-21.20.06.55.webm

Yes bien vu !

Heureusement pour nous la [v2.2.0](https://github.com/etalab/api-geo/releases/tag/v2.2.0) de l'API Géo renvoi désormais un département pour les COM. J'en ai profité pour retirer nos fallback.

2022-09-26 09:46 UTC, tmerlier approved these changes

2022-09-26 09:46 UTC, merged