Ajout des vidéos tutoriels mes-adresses
BaseAdresseNationale/mes-adresses pull request #695
Opened 2022-09-09 09:09 UTC by GllmR

Cette PR ajoute les tutoriels vidéos en provenance de [peertube.adresse.data.gouv.fr](peertube.adresse.data.gouv.fr)

- Dans la boite de dialogue d’accueil à la création d’une BAL
- Dans la boite de dialogue de récupération d’une BAL
- Dans chaque onglet de la partie "Besoin d’aide"

Ainsi qu’un lien vers le peertube dans le menu de navigation.

Le composant `VideoContainer` possède une fonction qui permet de transformer un lien de partage en vidéo intégrée.

Captures : 

![image](https://user-images.githubusercontent.com/56537238/189314271-c96905bb-9709-4c0e-9865-8d47512a4856.png)

![image](https://user-images.githubusercontent.com/56537238/189314320-e66f0721-2502-4d73-8ab7-360a7e47abf6.png)

![image](https://user-images.githubusercontent.com/56537238/189314543-75186555-843c-4dcb-b614-992cfdf8051d.png)

![image](https://user-images.githubusercontent.com/56537238/189314579-2a16d23a-cfae-4987-9afa-cdc57d453424.png)

2022-09-12 12:56 UTC, cedric-famibelle-pronzola requested changes
Le clique sur PeerTube devrait nous diriger vers l'instance, ce n'est pas le cas.

![Capture d’écran du 2022-09-12 16-53-23](https://user-images.githubusercontent.com/45098730/189658877-e4009a85-3827-40a8-8256-1ff49be5b0f9.png)

2022-09-12 12:56 UTC, cedric-famibelle-pronzola commented on components/help/video-container.js
> +  const embedCode = link.replace(`${TUBE_LINK}/w/`, '')
`link` contient l'intégralité de l'url. on pourrait juste passer le `shortUUID` (ce qui vient après /w/), en changeant le nom de la props.
ça éviterait d'utiliser `link.remplace`

2022-09-12 12:56 UTC, cedric-famibelle-pronzola commented on components/help/video-container.js
> +        height='315px'
L'avertissement peut être utile si on peut l'afficher en Français

2022-09-12 13:05 UTC, GllmR commented on components/help/video-container.js
> +        height='315px'
J’avais peur que ça déstabilise les utilisateurs qui pourraient s'inquiéter du partage de leur adresse IP.

Au cas où, il est disponible en Français.

2022-09-12 13:07 UTC, cedric-famibelle-pronzola commented on components/help/video-container.js
> +        height='315px'
ok. à voir en fonction de la RGPD

2022-09-13 07:41 UTC, cedric-famibelle-pronzola approved these changes

2022-09-13 08:12 UTC, tmerlier requested changes

2022-09-13 08:12 UTC, tmerlier commented on components/help/video-container.js
> +const TUBE_LINK = 'https://peertube.adresse.data.gouv.fr'
Ce lien devrait être une variable d'environnement partout.

2022-09-13 08:12 UTC, tmerlier commented on components/welcome-message.js
> +      />
Quand la popup s'ouvre, la vidéo n'est pas visible. Il serait peut-être mieux de la placer avant le texte, car les gros pavés de texte ne sont généralement pas lus.

Je la placerai juste après le titre `ous souhaitez mettre à jour les adresses de votre commune ? Vous êtes au bon endroit ! 🎉`

2022-09-13 08:12 UTC, tmerlier commented on components/welcome-message.js
> +      />
Je retirerai aussi le titre de la vidéo `Introduction à mes-adresses :` pour alléger un peu si possible.

2022-09-13 09:02 UTC, tmerlier requested changes
La variable d'environnement doit être présente partout où le lien est utilisé. La récupération de cette variable d'environnement doit être également avoir un fallback si jamais celle-ci n'est pas défini.

Pour éviter la redondance de : 
```
const PEERTUBE_LINK = process.env.NEXT_PUBLIC_PEERTUBE || 'https://peertube.adresse.data.gouv.fr'
```
Cette variable pourrait être déclaré et exporté depuis un fichier dédié comme `video-container.js` par exemple.

2022-09-14 09:36 UTC, tmerlier approved these changes

2022-09-14 09:44 UTC, merged