Corrige les erreurs affichées dans la console du navigateur
BaseAdresseNationale/mes-adresses pull request #696
Opened 2022-09-13 08:58 UTC by GllmR

Cette pull-request corrige plusieurs erreurs qui apparaissent dans la console du navigateur : 

- ` Failed prop type: Invalid prop 'isShown' of type 'string' supplied to 'Overlay', expected 'boolean'`
- `Failed prop type: The prop 'isEditionDisabled' is marked as required in 'NumerosList', but its value is 'undefined'.`
- `Received 'true' for a non-boolean attribute 'alt'.`

2022-09-14 07:59 UTC, cedric-famibelle-pronzola reviewed
Il reste 2 erreurs qui s'affichent en arrivant sur la page `/new`

- 1 
![Capture d’écran du 2022-09-14 11-54-06](https://user-images.githubusercontent.com/45098730/190095298-cd8aeb6c-1400-4bc9-8a51-e66fff47e3be.png)

- 2 
![Capture d’écran du 2022-09-14 11-54-30](https://user-images.githubusercontent.com/45098730/190095350-018d2aed-2928-49dd-9f9c-514f69926045.png)

2022-09-14 08:26 UTC, GllmR commented
> Il reste 2 erreurs qui s'affichent en arrivant sur la page `/new`
> 
>     * 1
>       ![Capture d’écran du 2022-09-14 11-54-06](https://user-images.githubusercontent.com/45098730/190095298-cd8aeb6c-1400-4bc9-8a51-e66fff47e3be.png)
> 
>     * 2
>       ![Capture d’écran du 2022-09-14 11-54-30](https://user-images.githubusercontent.com/45098730/190095350-018d2aed-2928-49dd-9f9c-514f69926045.png)

La première vient du "hack" pour chrome [ici](https://github.com/BaseAdresseNationale/mes-adresses/blob/b6627f48b44a2928e337f6e025814f43ab302fb0/components/new/create-form.js#L97)

La deuxième est un [bug d’evergreen](https://github.com/segmentio/evergreen/issues/842) 😇

2022-09-14 08:53 UTC, cedric-famibelle-pronzola approved these changes

2022-09-21 14:44 UTC, tmerlier requested changes

2022-09-21 14:44 UTC, tmerlier commented on pages/accessibilite.js
> +        <Image src='/static/images/accessibilite-illustration.svg' layout='responsive' height={100} width={500} alt='true' />
Le `alt` doit décrire l'image si elle contient des informations. Ici l'image est une icône "décoration" donc le champ doit être présent, mais peut-être vide.

```suggestion
        <Image src='/static/images/accessibilite-illustration.svg' layout='responsive' height={100} width={500} alt='' />
```

2022-09-21 14:44 UTC, tmerlier commented on components/welcome-message.js
> +      isShown={isShown && Boolean(token)}
```suggestion
      isShown={Boolean(isShown && token)}
```

2022-09-22 09:35 UTC, tmerlier approved these changes

2022-09-22 09:35 UTC, merged