Indique si les adresses d'une voie sont toutes certifiées
BaseAdresseNationale/mes-adresses pull request #700
Opened 2022-09-19 15:28 UTC by cedric-famibelle-pronzola

# ⚠️ Liée à la PR mes-adresses-api #

Resolves #572 

[Capture vidéo 2022-09-19 19:21:11.webm](https://user-images.githubusercontent.com/45098730/191054281-613faebe-1666-44d6-9ad3-db8e27273450.webm)

2022-09-22 13:09 UTC, GllmR reviewed
Je remarque que lorsqu’on certifie les adresses en passant par les paramètres, il faut recharger pour voir apparaître les "badges".
Est-ce qu’on pourrait recharger la liste des voies pour qu'ils s'affichent dès que la certification est effectuée ?

![image](https://user-images.githubusercontent.com/56537238/191756289-5f3057e8-2476-4fd9-8126-ad8fb0d0b3a1.png)

2022-09-22 13:22 UTC, tmerlier requested changes

2022-09-22 13:22 UTC, tmerlier commented on components/table-row/table-row-notifications.js
> +          <Tooltip content={`${certificationContent || 'Cette adresse est certifiée par la commune'}`} position={Position.BOTTOM}>
Je remplacerai `isCertified` par `certification`. Si `certification` n'est pas `null` alors c'est que l'adresse est certifiée, on s'évite des `states` en plus qui font doublon.

2022-09-22 13:22 UTC, tmerlier commented on components/bal/voies-list.js
> +            }}
Nous pourrions rajouter un avertissement dans le cas où la voie n'a pas de numéro, cela permettrait de fermer ce ticket #684

2022-09-23 08:30 UTC, GllmR approved these changes

2022-09-23 08:35 UTC, tmerlier approved these changes

2022-09-23 09:16 UTC, Maxine-Le-Pennec approved these changes

2022-09-23 13:58 UTC, merged