Empèche le panneau d’information de la carte de couvrir les contrôles
BaseAdresseNationale/mes-adresses pull request #701
Opened 2022-09-20 10:24 UTC by GllmR

Cette pull-request modifie le comportement du panneau informatif qui couvre les contrôles de la carte et du panneau d’édition.

Le composant a été déplacé afin de pourvoir être mieux disposé au-dessus de la carte sans empêcher l’utilisation des boutons de contrôle.

### Avant : 

https://user-images.githubusercontent.com/56537238/191232984-4e217c30-df31-451e-bd62-c436df6f65a6.mov

### Après : 

https://user-images.githubusercontent.com/56537238/191233045-f1692642-5d8a-4562-aef3-93d29687b1ab.mov

2022-09-21 12:52 UTC, cedric-famibelle-pronzola reviewed
Le panneau empêche également le tracé

[capture-mes-adresses.webm](https://user-images.githubusercontent.com/45098730/191508133-d4ae636b-6064-439f-aa3d-3bdd5f5949d5.webm)

2022-09-21 13:05 UTC, Maxine-Le-Pennec commented
> > Le panneau empêche également le tracé
> > capture-mes-adresses.webm
> 
> Effectivement, c’était pire avant, je n’ai pas trouvé de solution pour contourner ce problème, je suis preneur si vous voyez une alternative. Je pensais éventuellement à modifier les valeurs de la PR sur les tracés de voie pour déplacer la carte lorsqu'on arrive dans la partie "vide"

À part pour te faire des tests fonctionnels, je vais avoir du mal à trouver une piste :'(

2022-09-21 13:42 UTC, cedric-famibelle-pronzola commented
> > Le panneau empêche également le tracé
> > capture-mes-adresses.webm
> 
> Effectivement, c’était pire avant, je n’ai pas trouvé de solution pour contourner ce problème, je suis preneur si vous voyez une alternative. Je pensais éventuellement à modifier les valeurs de la PR sur les tracés de voie pour déplacer la carte lorsqu'on arrive dans la partie "vide"

effectivement on pourrait déplacer la carte. ce serait une autre PR du coup, non ?

2022-09-22 09:10 UTC, cedric-famibelle-pronzola approved these changes

2022-09-22 10:04 UTC, tmerlier requested changes

2022-09-22 10:04 UTC, tmerlier commented on components/map/map.js
> +          left='55%'
Je propose : 
- de supprimer le `width` car il n'est pas obligatoire, la fenêtre s'adapte à la taille du message.
- de mettre `top` à 130px pour être aligné avec les contrôles de la carte et le bouton de fermeture du menu.
- Utiliser `align-self` pour ne pas avoir de nombre magique 

```suggestion
          zIndex={1}
          position='fixed'
          alignSelf='center'
          top={130}
```

2022-09-22 14:01 UTC, tmerlier approved these changes

2022-09-22 14:01 UTC, merged