Montre les commentaires des adresses dans la liste des voies et des toponymes
BaseAdresseNationale/mes-adresses pull request #706
Opened 2022-09-27 09:11 UTC by cedric-famibelle-pronzola

# ⚠️ Ne pas merger. Liée à la PR mes-adresses-api

Resolves #348 

[display-comments.webm](https://user-images.githubusercontent.com/45098730/192480896-aa65e618-3d42-44e8-a179-f2aba7db78f0.webm)

2022-09-27 15:48 UTC, tmerlier requested changes

2022-09-27 15:48 UTC, tmerlier commented on components/comments-content.js
> +  const filteredComments = comments.length > COMMENTS_LIMIT ? comments.slice(0, COMMENTS_LIMIT) : comments
```suggestion
  const filteredComments = comments.slice(0, COMMENTS_LIMIT)
```

2022-09-27 15:48 UTC, tmerlier commented on components/table-row/table-row-notifications.js
> +  comment: PropTypes.node,
On doit avoir un avertissement dans le cas des numéros non ?
On pourrait utiliser `oneOfType` :
```suggestion
  comment: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
```

2022-09-27 15:48 UTC, tmerlier commented on components/comments-content.js
> +          Commentaire{`${filteredComments.length > 0 ? 's' : ''}`}
Ça ne change pas grand-chose, on est d'accord, mais c'est logique.
```suggestion
          Commentaire{`${comments.length > 0 ? 's' : ''}`}
```

2022-09-27 15:48 UTC, tmerlier commented on components/comments-content.js
> +  return comments.map(({_id, numero, suffixe, comment}) => (
Il s'agit de quel `_id` ici ? Celui du numéro ?

2022-09-28 05:41 UTC, cedric-famibelle-pronzola commented on components/comments-content.js
> +  return comments.map(({_id, numero, suffixe, comment}) => (
oui c'est l'id du numéro

2022-09-28 09:48 UTC, GllmR approved these changes

2022-09-28 11:40 UTC, tmerlier approved these changes

2022-09-28 11:49 UTC, tmerlier commented
Après usage, je me dis que ce n'est pas une évidence qu'il s'agit des commentaires des numéros. Je vais voir pour modifier un peu l'interface pour que ce soit plus clair.

2022-09-30 13:57 UTC, merged