Mise en place d'une pagination sur la page /all
BaseAdresseNationale/mes-adresses pull request #720
Opened 2022-10-21 16:20 UTC by tmerlier

## Contexte
Cette PR utilise l'évolution apportée par BaseAdresseNationale/mes-adresses-api/pull/365 afin de mettre en place une pagination sur la page `/all` et améliorer les performances de celle-ci.

## Modifications
- La méthode `listBasesLocales` a été renommé `getBasesLocales`
- La méthode `searchBAL` a été renommé `searchBasesLocale`
- La méthode `searchBasesLocale` demande `deleted: 0` par défaut en query afin de filtrer les bases locales supprimées.

----------

⚠️ Cette PR nécessite les évolutions apportées par BaseAdresseNationale/mes-adresses-api/pull/365

2022-10-25 15:54 UTC, GllmR approved these changes

2022-10-26 06:23 UTC, cedric-famibelle-pronzola requested changes
La recherche ne fonctionne plus

2022-10-26 06:27 UTC, cedric-famibelle-pronzola commented
> La recherche ne fonctionne plus

Ah si, je n'étais pas à jour 🙄
Cependant elle retourne toujours "Aucun résultat"

2022-10-26 06:53 UTC, tmerlier commented
> > La recherche ne fonctionne plus
> 
> Ah si, je n'étais pas à jour 🙄 Cependant elle retourne toujours "Aucun résultat"

Si c'est simplement qu'elle ne fonctionne que sur un match parfait.

2022-10-26 07:42 UTC, cedric-famibelle-pronzola commented
> > > La recherche ne fonctionne plus
> > 
> > 
> > Ah si, je n'étais pas à jour roll_eyes Cependant elle retourne toujours "Aucun résultat"
> 
> Si c'est simplement qu'elle ne fonctionne que sur un match parfait.

Ah oui effectivement

2022-10-26 08:09 UTC, cedric-famibelle-pronzola approved these changes

2022-12-01 16:27 UTC, merged