Ajouter un overlay pour griser l'écran tant que tout n'est pas charger
BaseAdresseNationale/mes-adresses pull request #763
Opened 2023-04-04 05:51 UTC by fufeck

2023-04-04 08:01 UTC, tmerlier reviewed
L'overlay empêche toute interaction avec le `<Tooltip />` de l'en-tête donc son message est impossible à lire.

Je te propose de simplifier tout ça et de simplement afficher l'overlay avec le message `Chargement de la Base Adresse Locale` sous le `<Spinner />`. Quand le chargement est en cours, le tooltip ne s'affiche pas.

2023-04-05 12:20 UTC, tmerlier commented
On règle le problème de l'affichage inutile du `édition impossible`, malheureusement il nous reste le temps de récupération de l'habilitation qui pose défaut.
https://user-images.githubusercontent.com/7040549/230076703-ee6601e0-8168-48cc-90e0-56eaac8e42d1.mov

2023-04-11 13:35 UTC, MaGOs92 requested changes

2023-04-11 13:35 UTC, MaGOs92 commented on components/overlay.js
> +      { (tokenIsCheckin || habilitationIsLoading) && (
Je pense que ça serait mieux de créer un composant Overlay sans la logique d'affichage. Comme ça on pourra le réutiliser plus facilement.

Du coup plus besoin d'importer les contextes dedans, dans le composant parent qui appelle Overlay, tu aurais : 
`{(tokenIsCheckin || habilitationIsLoading) && <Overlay text="Chargement de la Base...." /> }`

ou si tu préfères avoir une prop isShown pour gérer l'affichage (comme pour le composant Dialog)

2023-04-11 13:35 UTC, MaGOs92 commented on contexts/token.js
> +  const [tokenIsCheckin, setTokenIsCheckin] = useState(false)
Typo : tokenIsChecking

2023-04-14 12:40 UTC, tmerlier approved these changes

2023-04-14 15:14 UTC, MaGOs92 requested changes
Code : 1 commentaire

Tests : LGTM

2023-04-14 15:14 UTC, MaGOs92 commented on hooks/habilitation.js
> +    await reloadHabilitation()
Je crois pas que tu puisses utiliser de "await" dans le callback d'un useEffect. La technique c'est de déclarer une fonction async dedans et de l'appeler : 

```
useEffect(() => {
  async function handleReloadHabilitation() {
    setIsLoading(true)
    await reloadHabilitation()
    setIsLoading(false)
  }

  handleReloadHabilitation();
}, [token, reloadHabilitation]);
```

2023-04-17 14:07 UTC, merged