Mise à jour des dépendances
BaseAdresseNationale/mes-adresses pull request #769
Opened 2023-04-06 13:48 UTC by tmerlier

## Contexte
Mise à jour de toutes les dépendances qui ne présente pas d'incompatibilités majeures ou ne passant en ESM.

2023-04-07 12:39 UTC, MaGOs92 requested changes
Code LGTM,

Tests :

2023-04-07 12:40 UTC, MaGOs92 commented
Un warning est apparu dans la console : 
<img width="870" alt="Capture d’écran 2023-04-07 à 14 35 30" src="https://user-images.githubusercontent.com/4552238/230610512-93737460-eb5a-408e-85db-168ffc3a8990.png">

2023-04-07 12:41 UTC, MaGOs92 commented
La recherche me donne un résultat qui ne correspond pas au mot recherché, est-ce normal?
<img width="494" alt="Capture d’écran 2023-04-07 à 14 39 12" src="https://user-images.githubusercontent.com/4552238/230610641-9984cf5f-6233-48fd-8833-dcdf97e4efb7.png">

2023-04-10 08:00 UTC, fufeck commented
Relation avec l'issue https://github.com/BaseAdresseNationale/mes-adresses/issues/767

2023-04-11 09:29 UTC, fufeck reviewed
J'ai exactement comme Maxime `Warning: Unsupported style property -webkit-font-smoothing. Did you mean WebkitFontSmoothing?` sur différentes pages, evergreen a l'air d'avoir un problème. Sinonras pour le dashboard et le reste

2023-04-11 11:34 UTC, fufeck approved these changes

2023-04-11 11:36 UTC, tmerlier commented
C'est une erreur qui est apportée par EvergreenUI, nous ne pouvons malheureusement pas faire sans. La MAJ de evergreen-ui corrige certain `warning` en échange celui-ci.

2023-04-12 11:39 UTC, tmerlier commented
J'ai rétrogradé Evergreen-ui en `v6.13.0` pour éviter ce bug d'affichage (seul constaté).

![Capture d’écran 2023-04-12 à 13 38 18](https://user-images.githubusercontent.com/7040549/231445949-81ea9761-8fa0-436f-8074-6d3d59050a53.png)

2023-04-13 08:00 UTC, MaGOs92 commented
Quand j'accède à l'autocomplete je tombe sur ce warning. Sinon ça m'a l'air bon, je n'ai pas constaté de régression.
<img width="893" alt="Capture d’écran 2023-04-13 à 09 58 20" src="https://user-images.githubusercontent.com/4552238/231693442-5a65975a-b672-4f79-89c9-a7abd7a87eae.png">

2023-04-14 12:07 UTC, merged