add trash
BaseAdresseNationale/mes-adresses pull request #783
Opened 2023-05-02 11:09 UTC by fufeck

## Context

https://github.com/BaseAdresseNationale/mes-adresses/issues/772

## Fonctionnalité

Création de la corbeille

## Relation

Ne peut pas être réaliser avant la PR https://github.com/BaseAdresseNationale/mes-adresses-api/pull/382

2023-05-13 10:53 UTC, MaGOs92 requested changes

2023-05-13 10:53 UTC, MaGOs92 commented on layouts/editor.js
> +                              <Heading paddingLeft={5} is='h3' color='#D14343'>Corbielle</Heading>
Typo : Corbeille
Plutôt que le code hexa pour la couleur y'a pas déjà une variable pour le rouge?

2023-05-13 10:53 UTC, MaGOs92 commented on layouts/editor.js
> +              <TrashContextProvider>
Est-ce qu'on a vraiment besoin d'un context pour la corbeille? Les données vont elles être utilisées à plusieurs endroits dans l'application?
Si non je préfère qu'on reste sur un hook useTrash, c'est plus lisible que d'avoir des contexts partout

2023-05-13 10:53 UTC, MaGOs92 commented on components/trash/restore-voie/index.js
> +  const restoreVoieWithNumero = useCallback(async () => {
Je déplacerais toutes les fonctions "métier" de la corbeille dans le hook useTrask

2023-05-13 10:53 UTC, MaGOs92 commented on components/trash/trash.js
> +  const onRestoreToponyme = useCallback(async toponyme => {
Peut être aussi importer ces fonctions depuis le hook useTrash, en gros je verrai bien un hook useTrash qui gère les appels API et pourquoi pas un contexte qui gère la data (à voir si le hook ne suffit pas)

2023-05-13 10:53 UTC, MaGOs92 commented on components/trash/table-row-deleted/index.js
> +const TableRow = React.memo(({label, nomAlt, isVoieDeleted, nbNumeros, actions}) => (
Je suis pas sûr que ça vaille le coût de mémoiser ce genre de petit composant (https://dmitripavlutin.com/use-react-memo-wisely/)

2023-05-13 10:55 UTC, MaGOs92 commented
Tests : undefined dans la liste des toponymes
<img width="552" alt="Capture d’écran 2023-05-13 à 12 25 19" src="https://github.com/BaseAdresseNationale/mes-adresses/assets/4552238/a6e0a7e3-16e8-4272-b78c-66b1bbdc96e2">

2023-05-15 06:02 UTC, fufeck commented on layouts/editor.js
> +                              <Heading paddingLeft={5} is='h3' color='#D14343'>Corbielle</Heading>
Je ne trouve pas!
Lui passer `danger` ou `red500` ne marche pas. Du coup je me suis inspiré du reste du code ( par exemple `/components/habilitation-process/strategy-selection/index.js`)

2023-05-15 09:55 UTC, fufeck commented on layouts/editor.js
> +              <TrashContextProvider>
J'ai enlevé le context

2023-05-15 09:56 UTC, fufeck commented on components/trash/restore-voie/index.js
> +  const restoreVoieWithNumero = useCallback(async () => {
Alright

2023-05-15 09:56 UTC, fufeck commented on components/trash/trash.js
> +  const onRestoreToponyme = useCallback(async toponyme => {
C'est fait

2023-05-15 10:11 UTC, fufeck commented on components/trash/table-row-deleted/index.js
> +const TableRow = React.memo(({label, nomAlt, isVoieDeleted, nbNumeros, actions}) => (
Pas faux!

2023-05-16 13:34 UTC, MaGOs92 commented on components/trash/list/voies-deleted-list.js
> +function VoiesListDelete({voiesDeleted, onRestore, onRemove}) {
Les deux composants VoiesListDelete et ToponymeListDelete sont très similaires (à part deux labels j'ai l'impression que c'est la même chose). Y'a pas moyen de les factoriser dans un même composant générique ScrollableList par exemple?

2023-05-16 13:34 UTC, MaGOs92 commented
Tests : 
- Y'a un problème de scroll dans la liste de restoration des numéros
<img width="640" alt="Capture d’écran 2023-05-16 à 15 33 03" src="https://github.com/BaseAdresseNationale/mes-adresses/assets/4552238/c4b4e463-7358-4404-982f-9d45a3aa6e71">

2023-05-17 10:56 UTC, fufeck commented on components/trash/restore-voie/index.js
> +      ('voie' + (selectedNumerosIds.length > 0 ? ' avec ' + selectedNumerosIds.length + ' numero(s)' : '')) :
J'ai amelioré un peu la lecture, mais je n'arrive pas a faire des ternaire imbriqué avec la syntaxe ${}

2023-05-17 10:56 UTC, fufeck commented
> Tests :
> 
> * Y'a un problème de scroll dans la liste de restoration des numéros
> * Pour le titre Corbeille et pas Corbielle
> * Comportement bizarre : même si aucun numéro ne match la recherche, tu peux les restorer
>   https://www.loom.com/share/5bfbabf25e7f42d69ed54e3a8cc0a015

Tout est réglé

2023-05-19 09:05 UTC, MaGOs92 requested changes
Code LGTM

2023-05-19 09:07 UTC, MaGOs92 approved these changes

2023-05-19 09:17 UTC, MaGOs92 commented
Tests : 
- C'est assez subjectif, mais je pense qu'il faudrait enlever le dialogue dès que l'utilisateur clique sur le bouton, sinon il peut cliquer plusieurs fois ou vouloir cliquer sur "Annuler" alors que l'entité a déjà été supprimée dans le back. 
https://www.loom.com/share/516d3865a8304d95bcb07952ebc64b9f

2023-05-22 05:52 UTC, fufeck commented
> Tests :
> 
> * C'est assez subjectif, mais je pense qu'il faudrait enlever le dialogue dès que l'utilisateur clique sur le bouton, sinon il peut cliquer plusieurs fois ou vouloir cliquer sur "Annuler" alors que l'entité a déjà été supprimée dans le back.
>   https://www.loom.com/share/516d3865a8304d95bcb07952ebc64b9f

C'est un problème de lenteur de l'api (on avait le même problème pour convertir une voie en toponyme). Ca n'a pas vraiment de rapport avec cette PR. Je vais faire une PR a coté, pour disabled les boutons en attendant que la requète soit effectué

2023-05-24 12:50 UTC, merged