feat: autocomplete numero voie metrique
BaseAdresseNationale/mes-adresses pull request #901
Opened 2024-04-12 10:40 UTC by fufeck

2024-04-16 09:44 UTC, MaGOs92 requested changes

2024-04-16 09:44 UTC, MaGOs92 commented on components/bal/numero-editor.tsx
> +  const [numero, setNumero] = useState<string>(
Attention, ça fait une régression sur le signalement

2024-04-16 09:54 UTC, MaGOs92 commented
Tests : Je vois plusieurs régressions : 
- Sur le signalement : https://www.loom.com/share/b58a3380402c409a838678a17f3c9bb0
- On ne voit plus le numéro à l'ouverture du formulaire et problème de refresh à l'édition du suffixe : https://www.loom.com/share/363c30ca6df541259127fdd22ee943cf
- Je pense qu'il faut autocomplete le champ numéro à la création mais pas à l'édition, si une personne veut ajuster une position elle ne doit pas changer de numéro (cage d'escalier, bâtiment, ...)

2024-04-19 14:10 UTC, MaGOs92 requested changes
Tests : 
- J'ai toujours le problème de l'autocomplete quand on bouge une position en mode édition.
- Il y'a un problème avec les suffixes, ils n'ont pas l'air d'être enregistrés
- J'ai aussi l'impression qu'il y'a une incohérence avec les numéros quand on clique sur annuler

https://www.loom.com/share/2c372b7d41904fe4946feb9bca23e287

2024-04-22 09:10 UTC, fufeck commented
> Tests :
> 
> * J'ai toujours le problème de l'autocomplete quand on bouge une position en mode édition.
> * Il y'a un problème avec les suffixes, ils n'ont pas l'air d'être enregistrés
> * J'ai aussi l'impression qu'il y'a une incohérence avec les numéros quand on clique sur annuler
> 
> https://www.loom.com/share/2c372b7d41904fe4946feb9bca23e287

J'ai bien corrigé les 2 premiers points mais je ne trouve pas le problème pour le troisième point

2024-04-23 08:01 UTC, MaGOs92 commented
Le signalement est tjs HS...
https://www.loom.com/share/f5a85f4ec6474f43a82e35c8e952c31b

2024-04-23 09:40 UTC, MaGOs92 requested changes
Le signalement est tjs HS...

https://www.loom.com/share/f5a85f4ec6474f43a82e35c8e952c31b

2024-04-24 13:35 UTC, fufeck commented
> Le signalement est tjs HS...
> 
> https://www.loom.com/share/f5a85f4ec6474f43a82e35c8e952c31b

Bon cette fois c'est bon tout est corrigé ;)

2024-04-25 08:21 UTC, MaGOs92 approved these changes
C'est bon pour moi!

2024-04-29 08:20 UTC, merged