Migration nestjs api depot
BaseAdresseNationale/mes-adresses pull request #924
Opened 2024-06-11 15:44 UTC by fufeck

## Modification
- Changement de traitement de la validation du code pin
- Génération des service openapi

2024-06-12 12:18 UTC, MaGOs92 requested changes

2024-06-12 12:18 UTC, MaGOs92 commented on components/habilitation-process/index.tsx
> +      toaster.danger("Le code n’est pas valide", {
Je comprends pas pourquoi avoir touché à ça? Tu m'as demandé de le faire dans la PR du toaster

2024-06-12 12:18 UTC, MaGOs92 commented on lib/openapi/services/HabilitationService.ts
> +     * @returns any
ça devrait pas renvoyer void plutôt?

2024-06-24 13:25 UTC, fufeck commented on lib/openapi/services/HabilitationService.ts
> +     * @returns any
C'est généré automatiquement en any

2024-07-02 12:56 UTC, merged